# Hand-maintained wrapper around func_8821DAC0's still-GLOBAL_ASM body.
# NOT auto-regenerated by `make extract` (splat only ever emits
# func_8821DAC0.s at this address, never this filename), so it's safe to
# carry the extra .late_rodata words below across re-extracts. See the
# comment on the GLOBAL_ASM pragma in fragment31_190BB0.c for why these
# words live here instead of as a plain C global.

.late_rodata
dlabel jtbl_882341B8
.word 0x8821EFB4
.word 0x8821EFB4

.text
glabel func_8821DAC0
    /* 190D40 8821DAC0 27BDFF90 */  addiu       $sp, $sp, -0x70
    /* 190D44 8821DAC4 AFB20060 */  sw          $s2, 0x60($sp)
    /* 190D48 8821DAC8 00809025 */  or          $s2, $a0, $zero
    /* 190D4C 8821DACC AFBF006C */  sw          $ra, 0x6C($sp)
    /* 190D50 8821DAD0 AFB40068 */  sw          $s4, 0x68($sp)
    /* 190D54 8821DAD4 AFB30064 */  sw          $s3, 0x64($sp)
    /* 190D58 8821DAD8 00A09825 */  or          $s3, $a1, $zero
    /* 190D5C 8821DADC 00C0A025 */  or          $s4, $a2, $zero
    /* 190D60 8821DAE0 AFB1005C */  sw          $s1, 0x5C($sp)
    /* 190D64 8821DAE4 AFB00058 */  sw          $s0, 0x58($sp)
    /* 190D68 8821DAE8 F7BA0050 */  sdc1        $fs3, 0x50($sp)
    /* 190D6C 8821DAEC F7B80048 */  sdc1        $fs2, 0x48($sp)
    /* 190D70 8821DAF0 F7B60040 */  sdc1        $fs1, 0x40($sp)
    /* 190D74 8821DAF4 F7B40038 */  sdc1        $fs0, 0x38($sp)
    /* 190D78 8821DAF8 0C0172A9 */  jal         func_8005CAA4
    /* 190D7C 8821DAFC 24040022 */   addiu      $a0, $zero, 0x22
    /* 190D80 8821DB00 00408825 */  or          $s1, $v0, $zero
    /* 190D84 8821DB04 0C014C8C */  jal         func_80053230
    /* 190D88 8821DB08 24040012 */   addiu      $a0, $zero, 0x12
    /* 190D8C 8821DB0C 00027040 */  sll         $t6, $v0, 1
    /* 190D90 8821DB10 01D11821 */  addu        $v1, $t6, $s1
    /* 190D94 8821DB14 24630072 */  addiu       $v1, $v1, 0x72
    /* 190D98 8821DB18 00032C00 */  sll         $a1, $v1, 16
    /* 190D9C 8821DB1C 00038400 */  sll         $s0, $v1, 16
    /* 190DA0 8821DB20 00052C03 */  sra         $a1, $a1, 16
    /* 190DA4 8821DB24 00108403 */  sra         $s0, $s0, 16
    /* 190DA8 8821DB28 00052880 */  sll         $a1, $a1, 2
    /* 190DAC 8821DB2C 0C000BAE */  jal         mem_pool_alloc
    /* 190DB0 8821DB30 02402025 */   or         $a0, $s2, $zero
    /* 190DB4 8821DB34 AE620000 */  sw          $v0, 0x0($s3)
    /* 190DB8 8821DB38 02402025 */  or          $a0, $s2, $zero
    /* 190DBC 8821DB3C 0C000BAE */  jal         mem_pool_alloc
    /* 190DC0 8821DB40 00102880 */   sll        $a1, $s0, 2
    /* 190DC4 8821DB44 3C01BF00 */  lui         $at, (0xBF000000 >> 16)
    /* 190DC8 8821DB48 4481D000 */  mtc1        $at, $fs3
    /* 190DCC 8821DB4C 3C013F00 */  lui         $at, (0x3F000000 >> 16)
    /* 190DD0 8821DB50 4481C000 */  mtc1        $at, $fs2
    /* 190DD4 8821DB54 3C014407 */  lui         $at, (0x44070000 >> 16)
    /* 190DD8 8821DB58 02609025 */  or          $s2, $s3, $zero
    /* 190DDC 8821DB5C 4481A000 */  mtc1        $at, $fs0
    /* 190DE0 8821DB60 4480B000 */  mtc1        $zero, $fs1
    /* 190DE4 8821DB64 AE820000 */  sw          $v0, 0x0($s4)
    /* 190DE8 8821DB68 24130002 */  addiu       $s3, $zero, 0x2
    /* 190DEC 8821DB6C 00008025 */  or          $s0, $zero, $zero
  .L8821DB70:
    /* 190DF0 8821DB70 0C0007FC */  jal         func_80001FF0
    /* 190DF4 8821DB74 00000000 */   nop
    /* 190DF8 8821DB78 0C0007FC */  jal         func_80001FF0
    /* 190DFC 8821DB7C 00408825 */   or         $s1, $v0, $zero
    /* 190E00 8821DB80 44822000 */  mtc1        $v0, $ft0
    /* 190E04 8821DB84 44915000 */  mtc1        $s1, $ft3
    /* 190E08 8821DB88 24090020 */  addiu       $t1, $zero, 0x20
    /* 190E0C 8821DB8C 468021A0 */  cvt.s.w     $ft1, $ft0
    /* 190E10 8821DB90 240A0020 */  addiu       $t2, $zero, 0x20
    /* 190E14 8821DB94 240B0F0C */  addiu       $t3, $zero, 0xF0C
    /* 190E18 8821DB98 240C0046 */  addiu       $t4, $zero, 0x46
    /* 190E1C 8821DB9C 46805420 */  cvt.s.w     $ft4, $ft3
    /* 190E20 8821DBA0 4606A203 */  div.s       $ft2, $fs0, $ft1
    /* 190E24 8821DBA4 4610A483 */  div.s       $ft5, $fs0, $ft4
    /* 190E28 8821DBA8 4608B03C */  c.lt.s      $fs1, $ft2
    /* 190E2C 8821DBAC 00000000 */  nop
    /* 190E30 8821DBB0 45020004 */  bc1fl       .L8821DBC4
    /* 190E34 8821DBB4 4600D006 */   mov.s      $fv0, $fs3
    /* 190E38 8821DBB8 10000002 */  b           .L8821DBC4
    /* 190E3C 8821DBBC 4600C006 */   mov.s      $fv0, $fs2
    /* 190E40 8821DBC0 4600D006 */  mov.s       $fv0, $fs3
  .L8821DBC4:
    /* 190E44 8821DBC4 46120100 */  add.s       $ft0, $fv0, $ft5
    /* 190E48 8821DBC8 26440008 */  addiu       $a0, $s2, 0x8
    /* 190E4C 8821DBCC 240F0017 */  addiu       $t7, $zero, 0x17
    /* 190E50 8821DBD0 2418000C */  addiu       $t8, $zero, 0xC
    /* 190E54 8821DBD4 4600218D */  trunc.w.s   $ft1, $ft0
    /* 190E58 8821DBD8 AFB80014 */  sw          $t8, 0x14($sp)
    /* 190E5C 8821DBDC AFAF0010 */  sw          $t7, 0x10($sp)
    /* 190E60 8821DBE0 02809025 */  or          $s2, $s4, $zero
    /* 190E64 8821DBE4 44083000 */  mfc1        $t0, $ft1
    /* 190E68 8821DBE8 24050001 */  addiu       $a1, $zero, 0x1
    /* 190E6C 8821DBEC 24060007 */  addiu       $a2, $zero, 0x7
    /* 190E70 8821DBF0 240700D2 */  addiu       $a3, $zero, 0xD2
    /* 190E74 8821DBF4 AFA9001C */  sw          $t1, 0x1C($sp)
    /* 190E78 8821DBF8 AFAA0020 */  sw          $t2, 0x20($sp)
    /* 190E7C 8821DBFC AFAB0024 */  sw          $t3, 0x24($sp)
    /* 190E80 8821DC00 AFAC0028 */  sw          $t4, 0x28($sp)
    /* 190E84 8821DC04 0E00071B */  jal         func_88001C6C
    /* 190E88 8821DC08 AFA80018 */   sw         $t0, 0x18($sp)
    /* 190E8C 8821DC0C 26100001 */  addiu       $s0, $s0, 0x1
    /* 190E90 8821DC10 1613FFD7 */  bne         $s0, $s3, .L8821DB70
    /* 190E94 8821DC14 00000000 */  nop
    /* 190E98 8821DC18 8FBF006C */  lw          $ra, 0x6C($sp)
    /* 190E9C 8821DC1C D7B40038 */  ldc1        $fs0, 0x38($sp)
    /* 190EA0 8821DC20 D7B60040 */  ldc1        $fs1, 0x40($sp)
    /* 190EA4 8821DC24 D7B80048 */  ldc1        $fs2, 0x48($sp)
    /* 190EA8 8821DC28 D7BA0050 */  ldc1        $fs3, 0x50($sp)
    /* 190EAC 8821DC2C 8FB00058 */  lw          $s0, 0x58($sp)
    /* 190EB0 8821DC30 8FB1005C */  lw          $s1, 0x5C($sp)
    /* 190EB4 8821DC34 8FB20060 */  lw          $s2, 0x60($sp)
    /* 190EB8 8821DC38 8FB30064 */  lw          $s3, 0x64($sp)
    /* 190EBC 8821DC3C 8FB40068 */  lw          $s4, 0x68($sp)
    /* 190EC0 8821DC40 03E00008 */  jr          $ra
    /* 190EC4 8821DC44 27BD0070 */   addiu      $sp, $sp, 0x70
