# Hand-maintained wrapper around func_87E085CC's still-GLOBAL_ASM body.
# NOT auto-regenerated by `make extract` (splat only ever emits
# func_87E085CC.s at this address, never this filename), so it's safe to
# carry the extra .late_rodata word below across re-extracts. See the
# comment on the GLOBAL_ASM pragma in fragment63_30B540.c for why this word
# lives here instead of as a plain C global.

.late_rodata
dlabel jtbl_87E1B59C
.word 0x87E08F74

.text
glabel func_87E085CC
    /* 30BF3C 87E085CC 27BDFFD8 */  addiu       $sp, $sp, -0x28
    /* 30BF40 87E085D0 AFBF001C */  sw          $ra, 0x1C($sp)
    /* 30BF44 87E085D4 AFB00018 */  sw          $s0, 0x18($sp)
    /* 30BF48 87E085D8 AFA5002C */  sw          $a1, 0x2C($sp)
    /* 30BF4C 87E085DC 240E0004 */  addiu       $t6, $zero, 0x4
    /* 30BF50 87E085E0 00808025 */  or          $s0, $a0, $zero
    /* 30BF54 87E085E4 0DF8000C */  jal         func_87E00030
    /* 30BF58 87E085E8 AC8E0004 */   sw         $t6, 0x4($a0)
    /* 30BF5C 87E085EC 8E040020 */  lw          $a0, 0x20($s0)
    /* 30BF60 87E085F0 8FAF002C */  lw          $t7, 0x2C($sp)
    /* 30BF64 87E085F4 24180001 */  addiu       $t8, $zero, 0x1
    /* 30BF68 87E085F8 90992182 */  lbu         $t9, 0x2182($a0)
    /* 30BF6C 87E085FC 01F81804 */  sllv        $v1, $t8, $t7
    /* 30BF70 87E08600 03234024 */  and         $t0, $t9, $v1
    /* 30BF74 87E08604 51000013 */  beql        $t0, $zero, .L87E08654
    /* 30BF78 87E08608 8E040020 */   lw         $a0, 0x20($s0)
    /* 30BF7C 87E0860C 0DF805B6 */  jal         func_87E016D8
    /* 30BF80 87E08610 AFA30020 */   sw         $v1, 0x20($sp)
    /* 30BF84 87E08614 24010001 */  addiu       $at, $zero, 0x1
    /* 30BF88 87E08618 1441000D */  bne         $v0, $at, .L87E08650
    /* 30BF8C 87E0861C 8FA30020 */   lw         $v1, 0x20($sp)
    /* 30BF90 87E08620 8E040020 */  lw          $a0, 0x20($s0)
    /* 30BF94 87E08624 8C892188 */  lw          $t1, 0x2188($a0)
    /* 30BF98 87E08628 29210007 */  slti        $at, $t1, 0x7
    /* 30BF9C 87E0862C 54200009 */  bnel        $at, $zero, .L87E08654
    /* 30BFA0 87E08630 8E040020 */   lw         $a0, 0x20($s0)
    /* 30BFA4 87E08634 808A2181 */  lb          $t2, 0x2181($a0)
    /* 30BFA8 87E08638 24010002 */  addiu       $at, $zero, 0x2
    /* 30BFAC 87E0863C 55410005 */  bnel        $t2, $at, .L87E08654
    /* 30BFB0 87E08640 8E040020 */   lw         $a0, 0x20($s0)
    /* 30BFB4 87E08644 0DF81EF4 */  jal         func_87E07BD0
    /* 30BFB8 87E08648 AFA30020 */   sw         $v1, 0x20($sp)
    /* 30BFBC 87E0864C 8FA30020 */  lw          $v1, 0x20($sp)
  .L87E08650:
    /* 30BFC0 87E08650 8E040020 */  lw          $a0, 0x20($s0)
  .L87E08654:
    /* 30BFC4 87E08654 8FAC002C */  lw          $t4, 0x2C($sp)
    /* 30BFC8 87E08658 908B2182 */  lbu         $t3, 0x2182($a0)
    /* 30BFCC 87E0865C 000C68C0 */  sll         $t5, $t4, 3
    /* 30BFD0 87E08660 01AC6823 */  subu        $t5, $t5, $t4
    /* 30BFD4 87E08664 01631024 */  and         $v0, $t3, $v1
    /* 30BFD8 87E08668 10400008 */  beqz        $v0, .L87E0868C
    /* 30BFDC 87E0866C 000D6880 */   sll        $t5, $t5, 2
    /* 30BFE0 87E08670 01AC6823 */  subu        $t5, $t5, $t4
    /* 30BFE4 87E08674 000D6980 */  sll         $t5, $t5, 6
    /* 30BFE8 87E08678 008D7021 */  addu        $t6, $a0, $t5
    /* 30BFEC 87E0867C 8DD806B8 */  lw          $t8, 0x6B8($t6)
    /* 30BFF0 87E08680 00187FC2 */  srl         $t7, $t8, 31
    /* 30BFF4 87E08684 15E0000C */  bnez        $t7, .L87E086B8
    /* 30BFF8 87E08688 00000000 */   nop
  .L87E0868C:
    /* 30BFFC 87E0868C 14400004 */  bnez        $v0, .L87E086A0
    /* 30C000 87E08690 24080004 */   addiu      $t0, $zero, 0x4
    /* 30C004 87E08694 24190005 */  addiu       $t9, $zero, 0x5
    /* 30C008 87E08698 1000002D */  b           .L87E08750
    /* 30C00C 87E0869C AE190014 */   sw         $t9, 0x14($s0)
  .L87E086A0:
    /* 30C010 87E086A0 AE080014 */  sw          $t0, 0x14($s0)
    /* 30C014 87E086A4 8FA5002C */  lw          $a1, 0x2C($sp)
    /* 30C018 87E086A8 0DF820F3 */  jal         func_87E083CC
    /* 30C01C 87E086AC 02002025 */   or         $a0, $s0, $zero
    /* 30C020 87E086B0 10000027 */  b           .L87E08750
    /* 30C024 87E086B4 00000000 */   nop
  .L87E086B8:
    /* 30C028 87E086B8 0DF82159 */  jal         func_87E08564
    /* 30C02C 87E086BC 8FA4002C */   lw         $a0, 0x2C($sp)
    /* 30C030 87E086C0 10400018 */  beqz        $v0, .L87E08724
    /* 30C034 87E086C4 02002025 */   or         $a0, $s0, $zero
    /* 30C038 87E086C8 02002025 */  or          $a0, $s0, $zero
    /* 30C03C 87E086CC 0DF820F3 */  jal         func_87E083CC
    /* 30C040 87E086D0 8FA5002C */   lw         $a1, 0x2C($sp)
    /* 30C044 87E086D4 1040000A */  beqz        $v0, .L87E08700
    /* 30C048 87E086D8 02002025 */   or         $a0, $s0, $zero
    /* 30C04C 87E086DC 02002025 */  or          $a0, $s0, $zero
    /* 30C050 87E086E0 0DF820D7 */  jal         func_87E0835C
    /* 30C054 87E086E4 8FA5002C */   lw         $a1, 0x2C($sp)
    /* 30C058 87E086E8 10400003 */  beqz        $v0, .L87E086F8
    /* 30C05C 87E086EC 24090001 */   addiu      $t1, $zero, 0x1
    /* 30C060 87E086F0 10000017 */  b           .L87E08750
    /* 30C064 87E086F4 AE000014 */   sw         $zero, 0x14($s0)
  .L87E086F8:
    /* 30C068 87E086F8 10000015 */  b           .L87E08750
    /* 30C06C 87E086FC AE090014 */   sw         $t1, 0x14($s0)
  .L87E08700:
    /* 30C070 87E08700 0DF820D7 */  jal         func_87E0835C
    /* 30C074 87E08704 8FA5002C */   lw         $a1, 0x2C($sp)
    /* 30C078 87E08708 10400004 */  beqz        $v0, .L87E0871C
    /* 30C07C 87E0870C 240B0003 */   addiu      $t3, $zero, 0x3
    /* 30C080 87E08710 240A0002 */  addiu       $t2, $zero, 0x2
    /* 30C084 87E08714 1000000E */  b           .L87E08750
    /* 30C088 87E08718 AE0A0014 */   sw         $t2, 0x14($s0)
  .L87E0871C:
    /* 30C08C 87E0871C 1000000C */  b           .L87E08750
    /* 30C090 87E08720 AE0B0014 */   sw         $t3, 0x14($s0)
  .L87E08724:
    /* 30C094 87E08724 0DF820F3 */  jal         func_87E083CC
    /* 30C098 87E08728 8FA5002C */   lw         $a1, 0x2C($sp)
    /* 30C09C 87E0872C 02002025 */  or          $a0, $s0, $zero
    /* 30C0A0 87E08730 0DF820D7 */  jal         func_87E0835C
    /* 30C0A4 87E08734 8FA5002C */   lw         $a1, 0x2C($sp)
    /* 30C0A8 87E08738 10400004 */  beqz        $v0, .L87E0874C
    /* 30C0AC 87E0873C 240D0003 */   addiu      $t5, $zero, 0x3
    /* 30C0B0 87E08740 240C0002 */  addiu       $t4, $zero, 0x2
    /* 30C0B4 87E08744 10000002 */  b           .L87E08750
    /* 30C0B8 87E08748 AE0C0014 */   sw         $t4, 0x14($s0)
  .L87E0874C:
    /* 30C0BC 87E0874C AE0D0014 */  sw          $t5, 0x14($s0)
  .L87E08750:
    /* 30C0C0 87E08750 0DF83548 */  jal         func_87E0D520
    /* 30C0C4 87E08754 2604008C */   addiu      $a0, $s0, 0x8C
    /* 30C0C8 87E08758 0DF83179 */  jal         func_87E0C5E4
    /* 30C0CC 87E0875C 26040060 */   addiu      $a0, $s0, 0x60
    /* 30C0D0 87E08760 0DF843AA */  jal         func_87E10EA8
    /* 30C0D4 87E08764 24040024 */   addiu      $a0, $zero, 0x24
    /* 30C0D8 87E08768 0DF843CB */  jal         func_87E10F2C
    /* 30C0DC 87E0876C 00002025 */   or         $a0, $zero, $zero
    /* 30C0E0 87E08770 0DF846CC */  jal         func_87E11B30
    /* 30C0E4 87E08774 8FA4002C */   lw         $a0, 0x2C($sp)
    /* 30C0E8 87E08778 0DF84AFA */  jal         func_87E12BE8
    /* 30C0EC 87E0877C 26040628 */   addiu      $a0, $s0, 0x628
    /* 30C0F0 87E08780 0DF854C9 */  jal         func_87E15324
    /* 30C0F4 87E08784 26040644 */   addiu      $a0, $s0, 0x644
    /* 30C0F8 87E08788 AE0007B8 */  sw          $zero, 0x7B8($s0)
    /* 30C0FC 87E0878C 24040003 */  addiu       $a0, $zero, 0x3
    /* 30C100 87E08790 2405008C */  addiu       $a1, $zero, 0x8C
    /* 30C104 87E08794 0DF805A3 */  jal         func_87E0168C
    /* 30C108 87E08798 24060014 */   addiu      $a2, $zero, 0x14
    /* 30C10C 87E0879C 8FBF001C */  lw          $ra, 0x1C($sp)
    /* 30C110 87E087A0 8FB00018 */  lw          $s0, 0x18($sp)
    /* 30C114 87E087A4 27BD0028 */  addiu       $sp, $sp, 0x28
    /* 30C118 87E087A8 03E00008 */  jr          $ra
    /* 30C11C 87E087AC 00000000 */   nop
