# Hand-maintained wrapper around func_83503720's still-GLOBAL_ASM body.
# NOT auto-regenerated by `make extract` (splat only ever emits
# func_83503720.s at this address, never this filename), so it's safe to
# carry the extra .late_rodata words below across re-extracts. See the
# comment on the GLOBAL_ASM pragma in fragment1_code.c for why these words
# live here instead of as a plain C global.

.late_rodata
dlabel jtbl_83503E64
.word 0x83503758
.word 0x835037D4
.word 0x8350383C

.text
glabel func_83503720
    /* 0AC1A0 83503720 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 0AC1A4 83503724 AFB00018 */  sw          $s0, 0x18($sp)
    /* 0AC1A8 83503728 3C108350 */  lui         $s0, %hi(D_83503BA8)
    /* 0AC1AC 8350372C 26103BA8 */  addiu       $s0, $s0, %lo(D_83503BA8)
    /* 0AC1B0 83503730 2C810005 */  sltiu       $at, $a0, 0x5
    /* 0AC1B4 83503734 AFBF001C */  sw          $ra, 0x1C($sp)
    /* 0AC1B8 83503738 10200058 */  beqz        $at, .L8350389C
    /* 0AC1BC 8350373C AE040000 */   sw         $a0, 0x0($s0)
    /* 0AC1C0 83503740 00047080 */  sll         $t6, $a0, 2
    /* 0AC1C4 83503744 3C018350 */  lui         $at, %hi(jtbl_83503E64)
    /* 0AC1C8 83503748 002E0821 */  addu        $at, $at, $t6
    /* 0AC1CC 8350374C 8C2E3E64 */  lw          $t6, %lo(jtbl_83503E64)($at)
    /* 0AC1D0 83503750 01C00008 */  jr          $t6
    /* 0AC1D4 83503754 00000000 */   nop
    /* 0AC1D8 83503758 3C018350 */  lui         $at, %hi(D_83503DAC)
    /* 0AC1DC 8350375C 0C002128 */  jal         StageContext_GetFadeMode
    /* 0AC1E0 83503760 AC203DAC */   sw         $zero, %lo(D_83503DAC)($at)
    /* 0AC1E4 83503764 1440004D */  bnez        $v0, .L8350389C
    /* 0AC1E8 83503768 3C028350 */   lui        $v0, %hi(D_83503E80)
    /* 0AC1EC 8350376C 24423E80 */  addiu       $v0, $v0, %lo(D_83503E80)
    /* 0AC1F0 83503770 84580004 */  lh          $t8, 0x4($v0)
    /* 0AC1F4 83503774 240F0002 */  addiu       $t7, $zero, 0x2
    /* 0AC1F8 83503778 AE0F0000 */  sw          $t7, 0x0($s0)
    /* 0AC1FC 8350377C 17000009 */  bnez        $t8, .L835037A4
    /* 0AC200 83503780 00000000 */   nop
    /* 0AC204 83503784 84590000 */  lh          $t9, 0x0($v0)
    /* 0AC208 83503788 24010001 */  addiu       $at, $zero, 0x1
    /* 0AC20C 8350378C 17210005 */  bne         $t9, $at, .L835037A4
    /* 0AC210 83503790 00000000 */   nop
    /* 0AC214 83503794 0C0087B6 */  jal         func_80021ED8
    /* 0AC218 83503798 24040058 */   addiu      $a0, $zero, 0x58
    /* 0AC21C 8350379C 10000003 */  b           .L835037AC
    /* 0AC220 835037A0 00000000 */   nop
  .L835037A4:
    /* 0AC224 835037A4 0C0087B6 */  jal         func_80021ED8
    /* 0AC228 835037A8 2404005F */   addiu      $a0, $zero, 0x5F
  .L835037AC:
    /* 0AC22C 835037AC 3C088350 */  lui         $t0, %hi(D_83503AC0)
    /* 0AC230 835037B0 8D083AC0 */  lw          $t0, %lo(D_83503AC0)($t0)
    /* 0AC234 835037B4 15000039 */  bnez        $t0, .L8350389C
    /* 0AC238 835037B8 00000000 */   nop
    /* 0AC23C 835037BC 0C0089B0 */  jal         func_800226C0
    /* 0AC240 835037C0 240400A5 */   addiu      $a0, $zero, 0xA5
    /* 0AC244 835037C4 24090001 */  addiu       $t1, $zero, 0x1
    /* 0AC248 835037C8 3C018350 */  lui         $at, %hi(D_83503AC0)
    /* 0AC24C 835037CC 10000033 */  b           .L8350389C
    /* 0AC250 835037D0 AC293AC0 */   sw         $t1, %lo(D_83503AC0)($at)
    /* 0AC254 835037D4 3C018350 */  lui         $at, %hi(D_83503F50)
    /* 0AC258 835037D8 AC203F50 */  sw          $zero, %lo(D_83503F50)($at)
    /* 0AC25C 835037DC 8E0A0014 */  lw          $t2, 0x14($s0)
    /* 0AC260 835037E0 24010001 */  addiu       $at, $zero, 0x1
    /* 0AC264 835037E4 3C048350 */  lui         $a0, %hi(D_83503DAC)
    /* 0AC268 835037E8 15410005 */  bne         $t2, $at, .L83503800
    /* 0AC26C 835037EC 00000000 */  nop
    /* 0AC270 835037F0 0CD40D9E */  jal         func_83503678
    /* 0AC274 835037F4 8C843DAC */   lw         $a0, %lo(D_83503DAC)($a0)
    /* 0AC278 835037F8 3C018350 */  lui         $at, %hi(D_83503DAC)
    /* 0AC27C 835037FC AC223DAC */  sw          $v0, %lo(D_83503DAC)($at)
  .L83503800:
    /* 0AC280 83503800 3C0B8350 */  lui         $t3, %hi(D_83503DAC)
    /* 0AC284 83503804 8D6B3DAC */  lw          $t3, %lo(D_83503DAC)($t3)
    /* 0AC288 83503808 2961177A */  slti        $at, $t3, 0x177A
    /* 0AC28C 8350380C 14200023 */  bnez        $at, .L8350389C
    /* 0AC290 83503810 00000000 */  nop
    /* 0AC294 83503814 0C008971 */  jal         func_800225C4
    /* 0AC298 83503818 24040002 */   addiu      $a0, $zero, 0x2
    /* 0AC29C 8350381C 240C0003 */  addiu       $t4, $zero, 0x3
    /* 0AC2A0 83503820 AE0C0000 */  sw          $t4, 0x0($s0)
    /* 0AC2A4 83503824 0C002229 */  jal         StageContext_SetClearColor
    /* 0AC2A8 83503828 24040001 */   addiu      $a0, $zero, 0x1
    /* 0AC2AC 8350382C 0C001ECD */  jal         StageFade_StartFromTransparent
    /* 0AC2B0 83503830 2404000F */   addiu      $a0, $zero, 0xF
    /* 0AC2B4 83503834 10000019 */  b           .L8350389C
    /* 0AC2B8 83503838 00000000 */  nop
    /* 0AC2BC 8350383C 0CD40D7C */  jal         func_835035F0
    /* 0AC2C0 83503840 00000000 */  nop
    /* 0AC2C4 83503844 10000015 */  b           .L8350389C
    /* 0AC2C8 83503848 00000000 */  nop
    /* 0AC2CC 8350384C 0C002128 */  jal         StageContext_GetFadeMode
    /* 0AC2D0 83503850 00000000 */  nop
    /* 0AC2D4 83503854 24010001 */  addiu       $at, $zero, 0x1
    /* 0AC2D8 83503858 14410010 */  bne         $v0, $at, .L8350389C
    /* 0AC2DC 8350385C 240D0002 */   addiu      $t5, $zero, 0x2
    /* 0AC2E0 83503860 3C048350 */  lui         $a0, %hi(D_83503F30)
    /* 0AC2E4 83503864 AE0D0008 */  sw          $t5, 0x8($s0)
    /* 0AC2E8 83503868 0DFC0D33 */  jal         func_87F034CC
    /* 0AC2EC 8350386C 24843F30 */   addiu      $a0, $a0, %lo(D_83503F30)
    /* 0AC2F0 83503870 240E0004 */  addiu       $t6, $zero, 0x4
    /* 0AC2F4 83503874 AE0E0000 */  sw          $t6, 0x0($s0)
    /* 0AC2F8 83503878 10000008 */  b           .L8350389C
    /* 0AC2FC 8350387C AE000010 */   sw         $zero, 0x10($s0)
    /* 0AC300 83503880 8E0F0010 */  lw          $t7, 0x10($s0)
    /* 0AC304 83503884 24080005 */  addiu       $t0, $zero, 0x5
    /* 0AC308 83503888 25F80001 */  addiu       $t8, $t7, 0x1
    /* 0AC30C 8350388C 2B010006 */  slti        $at, $t8, 0x6
    /* 0AC310 83503890 14200002 */  bnez        $at, .L8350389C
    /* 0AC314 83503894 AE180010 */   sw         $t8, 0x10($s0)
    /* 0AC318 83503898 AE080000 */  sw          $t0, 0x0($s0)
  .L8350389C:
    /* 0AC31C 8350389C 3C048350 */  lui         $a0, %hi(D_83503F58)
    /* 0AC320 835038A0 0DFC3713 */  jal         func_87F0DC4C
    /* 0AC324 835038A4 24843F58 */   addiu      $a0, $a0, %lo(D_83503F58)
    /* 0AC328 835038A8 8FBF001C */  lw          $ra, 0x1C($sp)
    /* 0AC32C 835038AC 8E020000 */  lw          $v0, 0x0($s0)
    /* 0AC330 835038B0 8FB00018 */  lw          $s0, 0x18($sp)
    /* 0AC334 835038B4 03E00008 */  jr          $ra
    /* 0AC338 835038B8 27BD0020 */   addiu      $sp, $sp, 0x20
