# Hand-maintained wrapper around func_8FB02A10's still-GLOBAL_ASM body.
# NOT auto-regenerated by `make extract` (splat only ever emits
# func_8FB02A10.s at this address, never this filename), so it's safe to
# carry the extra .late_rodata word below across re-extracts. See the
# comment on the GLOBAL_ASM pragma in fragment9_code.c for why this word
# lives here instead of as a plain C global.

.late_rodata
# Last (38th) entry of jtbl_8FB03D2C (used by this function's own switch,
# below). The data blob still emits the `jtbl_8FB03D2C` label and its
# first 37 entries at their normal address -- only this trailing word is
# carried here, to widen fragment9_code's new .rodata claim back to a
# 16-byte boundary ahead of func_8FB03164's own jtbl_8FB03DC4. See the
# comment on this function's GLOBAL_ASM pragma in fragment9_code.c.
.word 0x8FB02D48

.text
glabel func_8FB02A10
    /* 0D2E90 8FB02A10 27BDFFB0 */  addiu       $sp, $sp, -0x50
    /* 0D2E94 8FB02A14 AFBF0024 */  sw          $ra, 0x24($sp)
    /* 0D2E98 8FB02A18 AFB00020 */  sw          $s0, 0x20($sp)
    /* 0D2E9C 8FB02A1C AFA50054 */  sw          $a1, 0x54($sp)
    /* 0D2EA0 8FB02A20 8C980038 */  lw          $t8, 0x38($a0)
    /* 0D2EA4 8FB02A24 8C8F0030 */  lw          $t7, 0x30($a0)
    /* 0D2EA8 8FB02A28 00808025 */  or          $s0, $a0, $zero
    /* 0D2EAC 8FB02A2C 0018C900 */  sll         $t9, $t8, 4
    /* 0D2EB0 8FB02A30 0338C821 */  addu        $t9, $t9, $t8
    /* 0D2EB4 8FB02A34 0019C940 */  sll         $t9, $t9, 5
    /* 0D2EB8 8FB02A38 00994021 */  addu        $t0, $a0, $t9
    /* 0D2EBC 8FB02A3C 2509004C */  addiu       $t1, $t0, 0x4C
    /* 0D2EC0 8FB02A40 AFA90040 */  sw          $t1, 0x40($sp)
    /* 0D2EC4 8FB02A44 8C8A003C */  lw          $t2, 0x3C($a0)
    /* 0D2EC8 8FB02A48 00AF1026 */  xor         $v0, $a1, $t7
    /* 0D2ECC 8FB02A4C 2C420001 */  sltiu       $v0, $v0, 0x1
    /* 0D2ED0 8FB02A50 000A5880 */  sll         $t3, $t2, 2
    /* 0D2ED4 8FB02A54 016A5823 */  subu        $t3, $t3, $t2
    /* 0D2ED8 8FB02A58 000B5880 */  sll         $t3, $t3, 2
    /* 0D2EDC 8FB02A5C 016A5823 */  subu        $t3, $t3, $t2
    /* 0D2EE0 8FB02A60 000B58C0 */  sll         $t3, $t3, 3
    /* 0D2EE4 8FB02A64 012B6021 */  addu        $t4, $t1, $t3
    /* 0D2EE8 8FB02A68 258D0010 */  addiu       $t5, $t4, 0x10
    /* 0D2EEC 8FB02A6C 10400009 */  beqz        $v0, .L8FB02A94
    /* 0D2EF0 8FB02A70 AFAD003C */   sw         $t5, 0x3C($sp)
    /* 0D2EF4 8FB02A74 240400FF */  addiu       $a0, $zero, 0xFF
    /* 0D2EF8 8FB02A78 240500FF */  addiu       $a1, $zero, 0xFF
    /* 0D2EFC 8FB02A7C 00003025 */  or          $a2, $zero, $zero
    /* 0D2F00 8FB02A80 240700FF */  addiu       $a3, $zero, 0xFF
    /* 0D2F04 8FB02A84 0C0125CB */  jal         func_8004972C
    /* 0D2F08 8FB02A88 AFB00050 */   sw         $s0, 0x50($sp)
    /* 0D2F0C 8FB02A8C 10000008 */  b           .L8FB02AB0
    /* 0D2F10 8FB02A90 8FAE0054 */   lw         $t6, 0x54($sp)
  .L8FB02A94:
    /* 0D2F14 8FB02A94 240400FF */  addiu       $a0, $zero, 0xFF
    /* 0D2F18 8FB02A98 240500FF */  addiu       $a1, $zero, 0xFF
    /* 0D2F1C 8FB02A9C 240600FF */  addiu       $a2, $zero, 0xFF
    /* 0D2F20 8FB02AA0 240700FF */  addiu       $a3, $zero, 0xFF
    /* 0D2F24 8FB02AA4 0C0125CB */  jal         func_8004972C
    /* 0D2F28 8FB02AA8 AFB00050 */   sw         $s0, 0x50($sp)
    /* 0D2F2C 8FB02AAC 8FAE0054 */  lw          $t6, 0x54($sp)
  .L8FB02AB0:
    /* 0D2F30 8FB02AB0 3C188FB0 */  lui         $t8, %hi(D_8FB034A0)
    /* 0D2F34 8FB02AB4 271834A0 */  addiu       $t8, $t8, %lo(D_8FB034A0)
    /* 0D2F38 8FB02AB8 000E78C0 */  sll         $t7, $t6, 3
    /* 0D2F3C 8FB02ABC 01EE7821 */  addu        $t7, $t7, $t6
    /* 0D2F40 8FB02AC0 000F7880 */  sll         $t7, $t7, 2
    /* 0D2F44 8FB02AC4 01F88021 */  addu        $s0, $t7, $t8
    /* 0D2F48 8FB02AC8 96190000 */  lhu         $t9, 0x0($s0)
    /* 0D2F4C 8FB02ACC 2F210026 */  sltiu       $at, $t9, 0x26
    /* 0D2F50 8FB02AD0 1020019F */  beqz        $at, .L8FB03150
    /* 0D2F54 8FB02AD4 0019C880 */   sll        $t9, $t9, 2
    /* 0D2F58 8FB02AD8 3C018FB0 */  lui         $at, %hi(jtbl_8FB03D2C)
    /* 0D2F5C 8FB02ADC 00390821 */  addu        $at, $at, $t9
    /* 0D2F60 8FB02AE0 8C393D2C */  lw          $t9, %lo(jtbl_8FB03D2C)($at)
    /* 0D2F64 8FB02AE4 03200008 */  jr          $t9
    /* 0D2F68 8FB02AE8 00000000 */   nop
    /* 0D2F6C 8FB02AEC 3C048FB0 */  lui         $a0, %hi(D_8FB03DF0)
    /* 0D2F70 8FB02AF0 96050004 */  lhu         $a1, 0x4($s0)
    /* 0D2F74 8FB02AF4 96060006 */  lhu         $a2, 0x6($s0)
    /* 0D2F78 8FB02AF8 24080001 */  addiu       $t0, $zero, 0x1
    /* 0D2F7C 8FB02AFC AFA80010 */  sw          $t0, 0x10($sp)
    /* 0D2F80 8FB02B00 8C843DF0 */  lw          $a0, %lo(D_8FB03DF0)($a0)
    /* 0D2F84 8FB02B04 0C01238C */  jal         func_80048E30
    /* 0D2F88 8FB02B08 26070012 */   addiu      $a3, $s0, 0x12
    /* 0D2F8C 8FB02B0C 10000191 */  b           .L8FB03154
    /* 0D2F90 8FB02B10 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D2F94 8FB02B14 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D2F98 8FB02B18 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D2F9C 8FB02B1C 3C078FB0 */  lui         $a3, %hi(D_8FB03A70)
    /* 0D2FA0 8FB02B20 260A0012 */  addiu       $t2, $s0, 0x12
    /* 0D2FA4 8FB02B24 AFAA0010 */  sw          $t2, 0x10($sp)
    /* 0D2FA8 8FB02B28 24E73A70 */  addiu       $a3, $a3, %lo(D_8FB03A70)
    /* 0D2FAC 8FB02B2C 0C01257E */  jal         func_800495F8
    /* 0D2FB0 8FB02B30 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D2FB4 8FB02B34 8FA9003C */  lw          $t1, 0x3C($sp)
    /* 0D2FB8 8FB02B38 91220000 */  lbu         $v0, 0x0($t1)
    /* 0D2FBC 8FB02B3C 50400185 */  beql        $v0, $zero, .L8FB03154
    /* 0D2FC0 8FB02B40 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D2FC4 8FB02B44 0C012DE9 */  jal         func_8004B7A4
    /* 0D2FC8 8FB02B48 00402025 */   or         $a0, $v0, $zero
    /* 0D2FCC 8FB02B4C 8FAB003C */  lw          $t3, 0x3C($sp)
    /* 0D2FD0 8FB02B50 AFA2002C */  sw          $v0, 0x2C($sp)
    /* 0D2FD4 8FB02B54 0C019187 */  jal         func_8006461C
    /* 0D2FD8 8FB02B58 91640020 */   lbu        $a0, 0x20($t3)
    /* 0D2FDC 8FB02B5C 24010001 */  addiu       $at, $zero, 0x1
    /* 0D2FE0 8FB02B60 14410004 */  bne         $v0, $at, .L8FB02B74
    /* 0D2FE4 8FB02B64 8FAC003C */   lw         $t4, 0x3C($sp)
    /* 0D2FE8 8FB02B68 3C028FB0 */  lui         $v0, %hi(D_8FB03A7C)
    /* 0D2FEC 8FB02B6C 1000000B */  b           .L8FB02B9C
    /* 0D2FF0 8FB02B70 24423A7C */   addiu      $v0, $v0, %lo(D_8FB03A7C)
  .L8FB02B74:
    /* 0D2FF4 8FB02B74 0C019187 */  jal         func_8006461C
    /* 0D2FF8 8FB02B78 91840020 */   lbu        $a0, 0x20($t4)
    /* 0D2FFC 8FB02B7C 24010002 */  addiu       $at, $zero, 0x2
    /* 0D3000 8FB02B80 14410004 */  bne         $v0, $at, .L8FB02B94
    /* 0D3004 8FB02B84 3C038FB0 */   lui        $v1, %hi(D_8FB03A84)
    /* 0D3008 8FB02B88 3C038FB0 */  lui         $v1, %hi(D_8FB03A80)
    /* 0D300C 8FB02B8C 10000002 */  b           .L8FB02B98
    /* 0D3010 8FB02B90 24633A80 */   addiu      $v1, $v1, %lo(D_8FB03A80)
  .L8FB02B94:
    /* 0D3014 8FB02B94 24633A84 */  addiu       $v1, $v1, %lo(D_8FB03A84)
  .L8FB02B98:
    /* 0D3018 8FB02B98 00601025 */  or          $v0, $v1, $zero
  .L8FB02B9C:
    /* 0D301C 8FB02B9C 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3020 8FB02BA0 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3024 8FB02BA4 3C068FB0 */  lui         $a2, %hi(D_8FB03A74)
    /* 0D3028 8FB02BA8 24C63A74 */  addiu       $a2, $a2, %lo(D_8FB03A74)
    /* 0D302C 8FB02BAC AFA20010 */  sw          $v0, 0x10($sp)
    /* 0D3030 8FB02BB0 0C01256F */  jal         func_800495BC
    /* 0D3034 8FB02BB4 8FA7002C */   lw         $a3, 0x2C($sp)
    /* 0D3038 8FB02BB8 10000166 */  b           .L8FB03154
    /* 0D303C 8FB02BBC 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3040 8FB02BC0 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3044 8FB02BC4 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3048 8FB02BC8 3C078FB0 */  lui         $a3, %hi(D_8FB03A88)
    /* 0D304C 8FB02BCC 260D0012 */  addiu       $t5, $s0, 0x12
    /* 0D3050 8FB02BD0 AFAD0010 */  sw          $t5, 0x10($sp)
    /* 0D3054 8FB02BD4 24E73A88 */  addiu       $a3, $a3, %lo(D_8FB03A88)
    /* 0D3058 8FB02BD8 0C01257E */  jal         func_800495F8
    /* 0D305C 8FB02BDC 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D3060 8FB02BE0 8FAE003C */  lw          $t6, 0x3C($sp)
    /* 0D3064 8FB02BE4 91C40001 */  lbu         $a0, 0x1($t6)
    /* 0D3068 8FB02BE8 5080015A */  beql        $a0, $zero, .L8FB03154
    /* 0D306C 8FB02BEC 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3070 8FB02BF0 0C018D78 */  jal         func_800635E0
    /* 0D3074 8FB02BF4 00000000 */   nop
    /* 0D3078 8FB02BF8 3C048FB0 */  lui         $a0, %hi(D_8FB03DF0)
    /* 0D307C 8FB02BFC 96050004 */  lhu         $a1, 0x4($s0)
    /* 0D3080 8FB02C00 96060006 */  lhu         $a2, 0x6($s0)
    /* 0D3084 8FB02C04 240F0001 */  addiu       $t7, $zero, 0x1
    /* 0D3088 8FB02C08 AFAF0010 */  sw          $t7, 0x10($sp)
    /* 0D308C 8FB02C0C 8C843DF0 */  lw          $a0, %lo(D_8FB03DF0)($a0)
    /* 0D3090 8FB02C10 0C01238C */  jal         func_80048E30
    /* 0D3094 8FB02C14 00403825 */   or         $a3, $v0, $zero
    /* 0D3098 8FB02C18 1000014E */  b           .L8FB03154
    /* 0D309C 8FB02C1C 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D30A0 8FB02C20 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D30A4 8FB02C24 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D30A8 8FB02C28 3C078FB0 */  lui         $a3, %hi(D_8FB03A8C)
    /* 0D30AC 8FB02C2C 26180012 */  addiu       $t8, $s0, 0x12
    /* 0D30B0 8FB02C30 AFB80010 */  sw          $t8, 0x10($sp)
    /* 0D30B4 8FB02C34 24E73A8C */  addiu       $a3, $a3, %lo(D_8FB03A8C)
    /* 0D30B8 8FB02C38 0C01257E */  jal         func_800495F8
    /* 0D30BC 8FB02C3C 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D30C0 8FB02C40 8FA3003C */  lw          $v1, 0x3C($sp)
    /* 0D30C4 8FB02C44 96190000 */  lhu         $t9, 0x0($s0)
    /* 0D30C8 8FB02C48 00794021 */  addu        $t0, $v1, $t9
    /* 0D30CC 8FB02C4C 9102FFF9 */  lbu         $v0, -0x7($t0)
    /* 0D30D0 8FB02C50 1040013F */  beqz        $v0, .L8FB03150
    /* 0D30D4 8FB02C54 304500FF */   andi       $a1, $v0, 0xFF
    /* 0D30D8 8FB02C58 90640000 */  lbu         $a0, 0x0($v1)
    /* 0D30DC 8FB02C5C 9066001D */  lbu         $a2, 0x1D($v1)
    /* 0D30E0 8FB02C60 0C0190F3 */  jal         func_800643CC
    /* 0D30E4 8FB02C64 A3A5003B */   sb         $a1, 0x3B($sp)
    /* 0D30E8 8FB02C68 10400008 */  beqz        $v0, .L8FB02C8C
    /* 0D30EC 8FB02C6C 8FAA003C */   lw         $t2, 0x3C($sp)
    /* 0D30F0 8FB02C70 240400FF */  addiu       $a0, $zero, 0xFF
    /* 0D30F4 8FB02C74 240500FF */  addiu       $a1, $zero, 0xFF
    /* 0D30F8 8FB02C78 240600FF */  addiu       $a2, $zero, 0xFF
    /* 0D30FC 8FB02C7C 0C0125CB */  jal         func_8004972C
    /* 0D3100 8FB02C80 240700FF */   addiu      $a3, $zero, 0xFF
    /* 0D3104 8FB02C84 10000012 */  b           .L8FB02CD0
    /* 0D3108 8FB02C88 00000000 */   nop
  .L8FB02C8C:
    /* 0D310C 8FB02C8C 91440000 */  lbu         $a0, 0x0($t2)
    /* 0D3110 8FB02C90 93A5003B */  lbu         $a1, 0x3B($sp)
    /* 0D3114 8FB02C94 0C0190F3 */  jal         func_800643CC
    /* 0D3118 8FB02C98 24060064 */   addiu      $a2, $zero, 0x64
    /* 0D311C 8FB02C9C 10400008 */  beqz        $v0, .L8FB02CC0
    /* 0D3120 8FB02CA0 240400FF */   addiu      $a0, $zero, 0xFF
    /* 0D3124 8FB02CA4 240400FF */  addiu       $a0, $zero, 0xFF
    /* 0D3128 8FB02CA8 240500FF */  addiu       $a1, $zero, 0xFF
    /* 0D312C 8FB02CAC 24060064 */  addiu       $a2, $zero, 0x64
    /* 0D3130 8FB02CB0 0C0125CB */  jal         func_8004972C
    /* 0D3134 8FB02CB4 240700FF */   addiu      $a3, $zero, 0xFF
    /* 0D3138 8FB02CB8 10000005 */  b           .L8FB02CD0
    /* 0D313C 8FB02CBC 00000000 */   nop
  .L8FB02CC0:
    /* 0D3140 8FB02CC0 24050064 */  addiu       $a1, $zero, 0x64
    /* 0D3144 8FB02CC4 24060064 */  addiu       $a2, $zero, 0x64
    /* 0D3148 8FB02CC8 0C0125CB */  jal         func_8004972C
    /* 0D314C 8FB02CCC 240700FF */   addiu      $a3, $zero, 0xFF
  .L8FB02CD0:
    /* 0D3150 8FB02CD0 0C018B38 */  jal         func_80062CE0
    /* 0D3154 8FB02CD4 93A4003B */   lbu        $a0, 0x3B($sp)
    /* 0D3158 8FB02CD8 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D315C 8FB02CDC 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3160 8FB02CE0 0C01256F */  jal         func_800495BC
    /* 0D3164 8FB02CE4 00403025 */   or         $a2, $v0, $zero
    /* 0D3168 8FB02CE8 240400FF */  addiu       $a0, $zero, 0xFF
    /* 0D316C 8FB02CEC 240500FF */  addiu       $a1, $zero, 0xFF
    /* 0D3170 8FB02CF0 240600FF */  addiu       $a2, $zero, 0xFF
    /* 0D3174 8FB02CF4 0C0125CB */  jal         func_8004972C
    /* 0D3178 8FB02CF8 240700FF */   addiu      $a3, $zero, 0xFF
    /* 0D317C 8FB02CFC 10000115 */  b           .L8FB03154
    /* 0D3180 8FB02D00 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3184 8FB02D04 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3188 8FB02D08 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D318C 8FB02D0C 3C078FB0 */  lui         $a3, %hi(D_8FB03A90)
    /* 0D3190 8FB02D10 26090012 */  addiu       $t1, $s0, 0x12
    /* 0D3194 8FB02D14 AFA90010 */  sw          $t1, 0x10($sp)
    /* 0D3198 8FB02D18 24E73A90 */  addiu       $a3, $a3, %lo(D_8FB03A90)
    /* 0D319C 8FB02D1C 0C01257E */  jal         func_800495F8
    /* 0D31A0 8FB02D20 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D31A4 8FB02D24 8FAB003C */  lw          $t3, 0x3C($sp)
    /* 0D31A8 8FB02D28 3C068FB0 */  lui         $a2, %hi(D_8FB03A94)
    /* 0D31AC 8FB02D2C 24C63A94 */  addiu       $a2, $a2, %lo(D_8FB03A94)
    /* 0D31B0 8FB02D30 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D31B4 8FB02D34 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D31B8 8FB02D38 0C01256F */  jal         func_800495BC
    /* 0D31BC 8FB02D3C 95670006 */   lhu        $a3, 0x6($t3)
    /* 0D31C0 8FB02D40 10000104 */  b           .L8FB03154
    /* 0D31C4 8FB02D44 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D31C8 8FB02D48 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D31CC 8FB02D4C 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D31D0 8FB02D50 3C078FB0 */  lui         $a3, %hi(D_8FB03A9C)
    /* 0D31D4 8FB02D54 260C0012 */  addiu       $t4, $s0, 0x12
    /* 0D31D8 8FB02D58 AFAC0010 */  sw          $t4, 0x10($sp)
    /* 0D31DC 8FB02D5C 24E73A9C */  addiu       $a3, $a3, %lo(D_8FB03A9C)
    /* 0D31E0 8FB02D60 0C01257E */  jal         func_800495F8
    /* 0D31E4 8FB02D64 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D31E8 8FB02D68 8FAD003C */  lw          $t5, 0x3C($sp)
    /* 0D31EC 8FB02D6C 3C068FB0 */  lui         $a2, %hi(D_8FB03AA0)
    /* 0D31F0 8FB02D70 24C63AA0 */  addiu       $a2, $a2, %lo(D_8FB03AA0)
    /* 0D31F4 8FB02D74 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D31F8 8FB02D78 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D31FC 8FB02D7C 0C01256F */  jal         func_800495BC
    /* 0D3200 8FB02D80 95A7000C */   lhu        $a3, 0xC($t5)
    /* 0D3204 8FB02D84 100000F3 */  b           .L8FB03154
    /* 0D3208 8FB02D88 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D320C 8FB02D8C 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3210 8FB02D90 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3214 8FB02D94 3C078FB0 */  lui         $a3, %hi(D_8FB03AA8)
    /* 0D3218 8FB02D98 260E0012 */  addiu       $t6, $s0, 0x12
    /* 0D321C 8FB02D9C AFAE0010 */  sw          $t6, 0x10($sp)
    /* 0D3220 8FB02DA0 24E73AA8 */  addiu       $a3, $a3, %lo(D_8FB03AA8)
    /* 0D3224 8FB02DA4 0C01257E */  jal         func_800495F8
    /* 0D3228 8FB02DA8 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D322C 8FB02DAC 8FAF0050 */  lw          $t7, 0x50($sp)
    /* 0D3230 8FB02DB0 3C068FB0 */  lui         $a2, %hi(D_8FB03AAC)
    /* 0D3234 8FB02DB4 24C63AAC */  addiu       $a2, $a2, %lo(D_8FB03AAC)
    /* 0D3238 8FB02DB8 8DE70038 */  lw          $a3, 0x38($t7)
    /* 0D323C 8FB02DBC 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3240 8FB02DC0 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3244 8FB02DC4 0C01256F */  jal         func_800495BC
    /* 0D3248 8FB02DC8 24E70001 */   addiu      $a3, $a3, 0x1
    /* 0D324C 8FB02DCC 100000E1 */  b           .L8FB03154
    /* 0D3250 8FB02DD0 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3254 8FB02DD4 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3258 8FB02DD8 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D325C 8FB02DDC 3C078FB0 */  lui         $a3, %hi(D_8FB03AB0)
    /* 0D3260 8FB02DE0 26180012 */  addiu       $t8, $s0, 0x12
    /* 0D3264 8FB02DE4 AFB80010 */  sw          $t8, 0x10($sp)
    /* 0D3268 8FB02DE8 24E73AB0 */  addiu       $a3, $a3, %lo(D_8FB03AB0)
    /* 0D326C 8FB02DEC 0C01257E */  jal         func_800495F8
    /* 0D3270 8FB02DF0 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D3274 8FB02DF4 8FB90040 */  lw          $t9, 0x40($sp)
    /* 0D3278 8FB02DF8 3C068FB0 */  lui         $a2, %hi(D_8FB03AB4)
    /* 0D327C 8FB02DFC 24C63AB4 */  addiu       $a2, $a2, %lo(D_8FB03AB4)
    /* 0D3280 8FB02E00 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3284 8FB02E04 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3288 8FB02E08 0C01256F */  jal         func_800495BC
    /* 0D328C 8FB02E0C 9727000C */   lhu        $a3, 0xC($t9)
    /* 0D3290 8FB02E10 100000D0 */  b           .L8FB03154
    /* 0D3294 8FB02E14 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3298 8FB02E18 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D329C 8FB02E1C 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D32A0 8FB02E20 3C078FB0 */  lui         $a3, %hi(D_8FB03ABC)
    /* 0D32A4 8FB02E24 26080012 */  addiu       $t0, $s0, 0x12
    /* 0D32A8 8FB02E28 AFA80010 */  sw          $t0, 0x10($sp)
    /* 0D32AC 8FB02E2C 24E73ABC */  addiu       $a3, $a3, %lo(D_8FB03ABC)
    /* 0D32B0 8FB02E30 0C01257E */  jal         func_800495F8
    /* 0D32B4 8FB02E34 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D32B8 8FB02E38 8FAA003C */  lw          $t2, 0x3C($sp)
    /* 0D32BC 8FB02E3C 3C068FB0 */  lui         $a2, %hi(D_8FB03AC0)
    /* 0D32C0 8FB02E40 24C63AC0 */  addiu       $a2, $a2, %lo(D_8FB03AC0)
    /* 0D32C4 8FB02E44 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D32C8 8FB02E48 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D32CC 8FB02E4C 0C01256F */  jal         func_800495BC
    /* 0D32D0 8FB02E50 8D470008 */   lw         $a3, 0x8($t2)
    /* 0D32D4 8FB02E54 100000BF */  b           .L8FB03154
    /* 0D32D8 8FB02E58 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D32DC 8FB02E5C 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D32E0 8FB02E60 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D32E4 8FB02E64 3C078FB0 */  lui         $a3, %hi(D_8FB03AC4)
    /* 0D32E8 8FB02E68 26090012 */  addiu       $t1, $s0, 0x12
    /* 0D32EC 8FB02E6C AFA90010 */  sw          $t1, 0x10($sp)
    /* 0D32F0 8FB02E70 24E73AC4 */  addiu       $a3, $a3, %lo(D_8FB03AC4)
    /* 0D32F4 8FB02E74 0C01257E */  jal         func_800495F8
    /* 0D32F8 8FB02E78 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D32FC 8FB02E7C 960C0000 */  lhu         $t4, 0x0($s0)
    /* 0D3300 8FB02E80 8FAB003C */  lw          $t3, 0x3C($sp)
    /* 0D3304 8FB02E84 3C068FB0 */  lui         $a2, %hi(D_8FB03AC8)
    /* 0D3308 8FB02E88 000C6840 */  sll         $t5, $t4, 1
    /* 0D330C 8FB02E8C 016D7021 */  addu        $t6, $t3, $t5
    /* 0D3310 8FB02E90 95C7FFEE */  lhu         $a3, -0x12($t6)
    /* 0D3314 8FB02E94 24C63AC8 */  addiu       $a2, $a2, %lo(D_8FB03AC8)
    /* 0D3318 8FB02E98 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D331C 8FB02E9C 0C01256F */  jal         func_800495BC
    /* 0D3320 8FB02EA0 96050006 */   lhu        $a1, 0x6($s0)
    /* 0D3324 8FB02EA4 100000AB */  b           .L8FB03154
    /* 0D3328 8FB02EA8 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D332C 8FB02EAC 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3330 8FB02EB0 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3334 8FB02EB4 3C078FB0 */  lui         $a3, %hi(D_8FB03ACC)
    /* 0D3338 8FB02EB8 260F0012 */  addiu       $t7, $s0, 0x12
    /* 0D333C 8FB02EBC AFAF0010 */  sw          $t7, 0x10($sp)
    /* 0D3340 8FB02EC0 24E73ACC */  addiu       $a3, $a3, %lo(D_8FB03ACC)
    /* 0D3344 8FB02EC4 0C01257E */  jal         func_800495F8
    /* 0D3348 8FB02EC8 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D334C 8FB02ECC 8FB8003C */  lw          $t8, 0x3C($sp)
    /* 0D3350 8FB02ED0 3C068FB0 */  lui         $a2, %hi(D_8FB03AD0)
    /* 0D3354 8FB02ED4 24C63AD0 */  addiu       $a2, $a2, %lo(D_8FB03AD0)
    /* 0D3358 8FB02ED8 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D335C 8FB02EDC 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3360 8FB02EE0 0C01256F */  jal         func_800495BC
    /* 0D3364 8FB02EE4 97070016 */   lhu        $a3, 0x16($t8)
    /* 0D3368 8FB02EE8 1000009A */  b           .L8FB03154
    /* 0D336C 8FB02EEC 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3370 8FB02EF0 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3374 8FB02EF4 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3378 8FB02EF8 3C078FB0 */  lui         $a3, %hi(D_8FB03AD8)
    /* 0D337C 8FB02EFC 26190012 */  addiu       $t9, $s0, 0x12
    /* 0D3380 8FB02F00 AFB90010 */  sw          $t9, 0x10($sp)
    /* 0D3384 8FB02F04 24E73AD8 */  addiu       $a3, $a3, %lo(D_8FB03AD8)
    /* 0D3388 8FB02F08 0C01257E */  jal         func_800495F8
    /* 0D338C 8FB02F0C 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D3390 8FB02F10 8FA8003C */  lw          $t0, 0x3C($sp)
    /* 0D3394 8FB02F14 960A0000 */  lhu         $t2, 0x0($s0)
    /* 0D3398 8FB02F18 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D339C 8FB02F1C 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D33A0 8FB02F20 010A4821 */  addu        $t1, $t0, $t2
    /* 0D33A4 8FB02F24 91220003 */  lbu         $v0, 0x3($t1)
    /* 0D33A8 8FB02F28 3C068FB0 */  lui         $a2, %hi(D_8FB03ADC)
    /* 0D33AC 8FB02F2C 24C63ADC */  addiu       $a2, $a2, %lo(D_8FB03ADC)
    /* 0D33B0 8FB02F30 304700C0 */  andi        $a3, $v0, 0xC0
    /* 0D33B4 8FB02F34 304C003F */  andi        $t4, $v0, 0x3F
    /* 0D33B8 8FB02F38 AFAC0010 */  sw          $t4, 0x10($sp)
    /* 0D33BC 8FB02F3C 0C01256F */  jal         func_800495BC
    /* 0D33C0 8FB02F40 00073983 */   sra        $a3, $a3, 6
    /* 0D33C4 8FB02F44 10000083 */  b           .L8FB03154
    /* 0D33C8 8FB02F48 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D33CC 8FB02F4C 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D33D0 8FB02F50 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D33D4 8FB02F54 3C078FB0 */  lui         $a3, %hi(D_8FB03AE4)
    /* 0D33D8 8FB02F58 260B0012 */  addiu       $t3, $s0, 0x12
    /* 0D33DC 8FB02F5C AFAB0010 */  sw          $t3, 0x10($sp)
    /* 0D33E0 8FB02F60 24E73AE4 */  addiu       $a3, $a3, %lo(D_8FB03AE4)
    /* 0D33E4 8FB02F64 0C01257E */  jal         func_800495F8
    /* 0D33E8 8FB02F68 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D33EC 8FB02F6C 8FAD003C */  lw          $t5, 0x3C($sp)
    /* 0D33F0 8FB02F70 3C068FB0 */  lui         $a2, %hi(D_8FB03AE8)
    /* 0D33F4 8FB02F74 24C63AE8 */  addiu       $a2, $a2, %lo(D_8FB03AE8)
    /* 0D33F8 8FB02F78 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D33FC 8FB02F7C 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3400 8FB02F80 0C01256F */  jal         func_800495BC
    /* 0D3404 8FB02F84 91A70020 */   lbu        $a3, 0x20($t5)
    /* 0D3408 8FB02F88 10000072 */  b           .L8FB03154
    /* 0D340C 8FB02F8C 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3410 8FB02F90 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3414 8FB02F94 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3418 8FB02F98 3C078FB0 */  lui         $a3, %hi(D_8FB03AEC)
    /* 0D341C 8FB02F9C 260E0012 */  addiu       $t6, $s0, 0x12
    /* 0D3420 8FB02FA0 AFAE0010 */  sw          $t6, 0x10($sp)
    /* 0D3424 8FB02FA4 24E73AEC */  addiu       $a3, $a3, %lo(D_8FB03AEC)
    /* 0D3428 8FB02FA8 0C01257E */  jal         func_800495F8
    /* 0D342C 8FB02FAC 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D3430 8FB02FB0 96180000 */  lhu         $t8, 0x0($s0)
    /* 0D3434 8FB02FB4 8FAF003C */  lw          $t7, 0x3C($sp)
    /* 0D3438 8FB02FB8 3C068FB0 */  lui         $a2, %hi(D_8FB03AF0)
    /* 0D343C 8FB02FBC 0018C840 */  sll         $t9, $t8, 1
    /* 0D3440 8FB02FC0 01F94021 */  addu        $t0, $t7, $t9
    /* 0D3444 8FB02FC4 9507FFF0 */  lhu         $a3, -0x10($t0)
    /* 0D3448 8FB02FC8 24C63AF0 */  addiu       $a2, $a2, %lo(D_8FB03AF0)
    /* 0D344C 8FB02FCC 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3450 8FB02FD0 0C01256F */  jal         func_800495BC
    /* 0D3454 8FB02FD4 96050006 */   lhu        $a1, 0x6($s0)
    /* 0D3458 8FB02FD8 1000005E */  b           .L8FB03154
    /* 0D345C 8FB02FDC 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3460 8FB02FE0 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3464 8FB02FE4 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3468 8FB02FE8 3C078FB0 */  lui         $a3, %hi(D_8FB03AF8)
    /* 0D346C 8FB02FEC 260A0012 */  addiu       $t2, $s0, 0x12
    /* 0D3470 8FB02FF0 AFAA0010 */  sw          $t2, 0x10($sp)
    /* 0D3474 8FB02FF4 24E73AF8 */  addiu       $a3, $a3, %lo(D_8FB03AF8)
    /* 0D3478 8FB02FF8 0C01257E */  jal         func_800495F8
    /* 0D347C 8FB02FFC 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D3480 8FB03000 8FA9003C */  lw          $t1, 0x3C($sp)
    /* 0D3484 8FB03004 3C068FB0 */  lui         $a2, %hi(D_8FB03AFC)
    /* 0D3488 8FB03008 24C63AFC */  addiu       $a2, $a2, %lo(D_8FB03AFC)
    /* 0D348C 8FB0300C 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3490 8FB03010 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3494 8FB03014 0C01256F */  jal         func_800495BC
    /* 0D3498 8FB03018 9127001C */   lbu        $a3, 0x1C($t1)
    /* 0D349C 8FB0301C 1000004D */  b           .L8FB03154
    /* 0D34A0 8FB03020 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D34A4 8FB03024 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D34A8 8FB03028 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D34AC 8FB0302C 3C078FB0 */  lui         $a3, %hi(D_8FB03B04)
    /* 0D34B0 8FB03030 260C0012 */  addiu       $t4, $s0, 0x12
    /* 0D34B4 8FB03034 AFAC0010 */  sw          $t4, 0x10($sp)
    /* 0D34B8 8FB03038 24E73B04 */  addiu       $a3, $a3, %lo(D_8FB03B04)
    /* 0D34BC 8FB0303C 0C01257E */  jal         func_800495F8
    /* 0D34C0 8FB03040 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D34C4 8FB03044 8FAB003C */  lw          $t3, 0x3C($sp)
    /* 0D34C8 8FB03048 3C068FB0 */  lui         $a2, %hi(D_8FB03B08)
    /* 0D34CC 8FB0304C 24C63B08 */  addiu       $a2, $a2, %lo(D_8FB03B08)
    /* 0D34D0 8FB03050 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D34D4 8FB03054 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D34D8 8FB03058 0C01256F */  jal         func_800495BC
    /* 0D34DC 8FB0305C 9167001D */   lbu        $a3, 0x1D($t3)
    /* 0D34E0 8FB03060 1000003C */  b           .L8FB03154
    /* 0D34E4 8FB03064 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D34E8 8FB03068 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D34EC 8FB0306C 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D34F0 8FB03070 3C078FB0 */  lui         $a3, %hi(D_8FB03B10)
    /* 0D34F4 8FB03074 260D0012 */  addiu       $t5, $s0, 0x12
    /* 0D34F8 8FB03078 AFAD0010 */  sw          $t5, 0x10($sp)
    /* 0D34FC 8FB0307C 24E73B10 */  addiu       $a3, $a3, %lo(D_8FB03B10)
    /* 0D3500 8FB03080 0C01257E */  jal         func_800495F8
    /* 0D3504 8FB03084 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D3508 8FB03088 8FA7003C */  lw          $a3, 0x3C($sp)
    /* 0D350C 8FB0308C 3C068FB0 */  lui         $a2, %hi(D_8FB03B14)
    /* 0D3510 8FB03090 24C63B14 */  addiu       $a2, $a2, %lo(D_8FB03B14)
    /* 0D3514 8FB03094 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3518 8FB03098 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D351C 8FB0309C 0C01256F */  jal         func_800495BC
    /* 0D3520 8FB030A0 24E70034 */   addiu      $a3, $a3, 0x34
    /* 0D3524 8FB030A4 1000002B */  b           .L8FB03154
    /* 0D3528 8FB030A8 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D352C 8FB030AC 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3530 8FB030B0 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3534 8FB030B4 3C078FB0 */  lui         $a3, %hi(D_8FB03B18)
    /* 0D3538 8FB030B8 260E0012 */  addiu       $t6, $s0, 0x12
    /* 0D353C 8FB030BC AFAE0010 */  sw          $t6, 0x10($sp)
    /* 0D3540 8FB030C0 24E73B18 */  addiu       $a3, $a3, %lo(D_8FB03B18)
    /* 0D3544 8FB030C4 0C01257E */  jal         func_800495F8
    /* 0D3548 8FB030C8 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D354C 8FB030CC 8FB80050 */  lw          $t8, 0x50($sp)
    /* 0D3550 8FB030D0 8FAF0040 */  lw          $t7, 0x40($sp)
    /* 0D3554 8FB030D4 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D3558 8FB030D8 8F02003C */  lw          $v0, 0x3C($t8)
    /* 0D355C 8FB030DC 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D3560 8FB030E0 3C068FB0 */  lui         $a2, %hi(D_8FB03B1C)
    /* 0D3564 8FB030E4 0002C880 */  sll         $t9, $v0, 2
    /* 0D3568 8FB030E8 0322C823 */  subu        $t9, $t9, $v0
    /* 0D356C 8FB030EC 0019C880 */  sll         $t9, $t9, 2
    /* 0D3570 8FB030F0 0322C823 */  subu        $t9, $t9, $v0
    /* 0D3574 8FB030F4 0019C8C0 */  sll         $t9, $t9, 3
    /* 0D3578 8FB030F8 01F94021 */  addu        $t0, $t7, $t9
    /* 0D357C 8FB030FC 250A0044 */  addiu       $t2, $t0, 0x44
    /* 0D3580 8FB03100 AFAA0010 */  sw          $t2, 0x10($sp)
    /* 0D3584 8FB03104 24C63B1C */  addiu       $a2, $a2, %lo(D_8FB03B1C)
    /* 0D3588 8FB03108 0C01256F */  jal         func_800495BC
    /* 0D358C 8FB0310C 24470001 */   addiu      $a3, $v0, 0x1
    /* 0D3590 8FB03110 10000010 */  b           .L8FB03154
    /* 0D3594 8FB03114 8FBF0024 */   lw         $ra, 0x24($sp)
    /* 0D3598 8FB03118 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D359C 8FB0311C 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D35A0 8FB03120 3C078FB0 */  lui         $a3, %hi(D_8FB03B24)
    /* 0D35A4 8FB03124 26090012 */  addiu       $t1, $s0, 0x12
    /* 0D35A8 8FB03128 AFA90010 */  sw          $t1, 0x10($sp)
    /* 0D35AC 8FB0312C 24E73B24 */  addiu       $a3, $a3, %lo(D_8FB03B24)
    /* 0D35B0 8FB03130 0C01257E */  jal         func_800495F8
    /* 0D35B4 8FB03134 24060002 */   addiu      $a2, $zero, 0x2
    /* 0D35B8 8FB03138 3C068FB0 */  lui         $a2, %hi(D_8FB03B28)
    /* 0D35BC 8FB0313C 24C63B28 */  addiu       $a2, $a2, %lo(D_8FB03B28)
    /* 0D35C0 8FB03140 96040004 */  lhu         $a0, 0x4($s0)
    /* 0D35C4 8FB03144 96050006 */  lhu         $a1, 0x6($s0)
    /* 0D35C8 8FB03148 0C01256F */  jal         func_800495BC
    /* 0D35CC 8FB0314C 8FA70040 */   lw         $a3, 0x40($sp)
  .L8FB03150:
    /* 0D35D0 8FB03150 8FBF0024 */  lw          $ra, 0x24($sp)
  .L8FB03154:
    /* 0D35D4 8FB03154 8FB00020 */  lw          $s0, 0x20($sp)
    /* 0D35D8 8FB03158 27BD0050 */  addiu       $sp, $sp, 0x50
    /* 0D35DC 8FB0315C 03E00008 */  jr          $ra
    /* 0D35E0 8FB03160 00000000 */   nop
