# Hand-maintained wrapper around func_8130F2C4's still-GLOBAL_ASM body.
# NOT auto-regenerated by `make extract` (splat only ever emits
# func_8130F2C4.s at this address, never this filename), so it's safe to
# carry the extra .late_rodata words below across re-extracts. See the
# comment on the GLOBAL_ASM pragma in fragment14_104FC0.c for why these
# words live here instead of as a plain C global.

.late_rodata
.word .L8130F520
.word .L8130F520
.word .L8130F520

.text
glabel func_8130F2C4
    /* 107454 8130F2C4 27BDFF98 */  addiu       $sp, $sp, -0x68
    /* 107458 8130F2C8 AFBF002C */  sw          $ra, 0x2C($sp)
    /* 10745C 8130F2CC AFB00028 */  sw          $s0, 0x28($sp)
    /* 107460 8130F2D0 AFA5006C */  sw          $a1, 0x6C($sp)
    /* 107464 8130F2D4 AFA00060 */  sw          $zero, 0x60($sp)
    /* 107468 8130F2D8 908E0034 */  lbu         $t6, 0x34($a0)
    /* 10746C 8130F2DC 00808025 */  or          $s0, $a0, $zero
    /* 107470 8130F2E0 2DC10008 */  sltiu       $at, $t6, 0x8
    /* 107474 8130F2E4 10200024 */  beqz        $at, .L8130F378
    /* 107478 8130F2E8 000E7080 */   sll        $t6, $t6, 2
    /* 10747C 8130F2EC 3C018131 */  lui         $at, %hi(jtbl_81312820)
    /* 107480 8130F2F0 002E0821 */  addu        $at, $at, $t6
    /* 107484 8130F2F4 8C2E2820 */  lw          $t6, %lo(jtbl_81312820)($at)
    /* 107488 8130F2F8 01C00008 */  jr          $t6
    /* 10748C 8130F2FC 00000000 */   nop
  jlabel .L8130F300
    /* 107490 8130F300 0C4C3B25 */  jal         func_8130EC94
    /* 107494 8130F304 02002025 */   or         $a0, $s0, $zero
    /* 107498 8130F308 10000097 */  b           .L8130F568
    /* 10749C 8130F30C 8FBF002C */   lw         $ra, 0x2C($sp)
  jlabel .L8130F310
    /* 1074A0 8130F310 0C4C3B27 */  jal         func_8130EC9C
    /* 1074A4 8130F314 02002025 */   or         $a0, $s0, $zero
    /* 1074A8 8130F318 10000018 */  b           .L8130F37C
    /* 1074AC 8130F31C 8E0F0000 */   lw         $t7, 0x0($s0)
  jlabel .L8130F320
    /* 1074B0 8130F320 0C4C3C27 */  jal         func_8130F09C
    /* 1074B4 8130F324 02002025 */   or         $a0, $s0, $zero
    /* 1074B8 8130F328 10000014 */  b           .L8130F37C
    /* 1074BC 8130F32C 8E0F0000 */   lw         $t7, 0x0($s0)
  jlabel .L8130F330
    /* 1074C0 8130F330 0C4C3C61 */  jal         func_8130F184
    /* 1074C4 8130F334 02002025 */   or         $a0, $s0, $zero
    /* 1074C8 8130F338 10000010 */  b           .L8130F37C
    /* 1074CC 8130F33C 8E0F0000 */   lw         $t7, 0x0($s0)
  jlabel .L8130F340
    /* 1074D0 8130F340 0C4C3C3F */  jal         func_8130F0FC
    /* 1074D4 8130F344 02002025 */   or         $a0, $s0, $zero
    /* 1074D8 8130F348 1000000C */  b           .L8130F37C
    /* 1074DC 8130F34C 8E0F0000 */   lw         $t7, 0x0($s0)
  jlabel .L8130F350
    /* 1074E0 8130F350 0C4C3C86 */  jal         func_8130F218
    /* 1074E4 8130F354 02002025 */   or         $a0, $s0, $zero
    /* 1074E8 8130F358 10000008 */  b           .L8130F37C
    /* 1074EC 8130F35C 8E0F0000 */   lw         $t7, 0x0($s0)
  jlabel .L8130F360
    /* 1074F0 8130F360 0C4C3C9C */  jal         func_8130F270
    /* 1074F4 8130F364 02002025 */   or         $a0, $s0, $zero
    /* 1074F8 8130F368 10000004 */  b           .L8130F37C
    /* 1074FC 8130F36C 8E0F0000 */   lw         $t7, 0x0($s0)
  jlabel .L8130F370
    /* 107500 8130F370 0C4C3BE2 */  jal         func_8130EF88
    /* 107504 8130F374 02002025 */   or         $a0, $s0, $zero
  .L8130F378:
    /* 107508 8130F378 8E0F0000 */  lw          $t7, 0x0($s0)
  .L8130F37C:
    /* 10750C 8130F37C 02002025 */  or          $a0, $s0, $zero
    /* 107510 8130F380 11E00003 */  beqz        $t7, .L8130F390
    /* 107514 8130F384 24180001 */   addiu      $t8, $zero, 0x1
    /* 107518 8130F388 AFB80060 */  sw          $t8, 0x60($sp)
    /* 10751C 8130F38C AE000000 */  sw          $zero, 0x0($s0)
  .L8130F390:
    /* 107520 8130F390 0C4C33BC */  jal         func_8130CEF0
    /* 107524 8130F394 27A50058 */   addiu      $a1, $sp, 0x58
    /* 107528 8130F398 87B9005A */  lh          $t9, 0x5A($sp)
    /* 10752C 8130F39C 87A8005C */  lh          $t0, 0x5C($sp)
    /* 107530 8130F3A0 87A9005E */  lh          $t1, 0x5E($sp)
    /* 107534 8130F3A4 8FA4006C */  lw          $a0, 0x6C($sp)
    /* 107538 8130F3A8 02002825 */  or          $a1, $s0, $zero
    /* 10753C 8130F3AC 8FA60060 */  lw          $a2, 0x60($sp)
    /* 107540 8130F3B0 87A70058 */  lh          $a3, 0x58($sp)
    /* 107544 8130F3B4 AFB90010 */  sw          $t9, 0x10($sp)
    /* 107548 8130F3B8 AFA80014 */  sw          $t0, 0x14($sp)
    /* 10754C 8130F3BC 0C58028D */  jal         func_81600A34
    /* 107550 8130F3C0 AFA90018 */   sw         $t1, 0x18($sp)
    /* 107554 8130F3C4 02002025 */  or          $a0, $s0, $zero
    /* 107558 8130F3C8 27A50040 */  addiu       $a1, $sp, 0x40
    /* 10755C 8130F3CC 0C4C3517 */  jal         func_8130D45C
    /* 107560 8130F3D0 27A60058 */   addiu      $a2, $sp, 0x58
    /* 107564 8130F3D4 82060038 */  lb          $a2, 0x38($s0)
    /* 107568 8130F3D8 87AA0042 */  lh          $t2, 0x42($sp)
    /* 10756C 8130F3DC 87AB0044 */  lh          $t3, 0x44($sp)
    /* 107570 8130F3E0 87AC0046 */  lh          $t4, 0x46($sp)
    /* 107574 8130F3E4 28C60000 */  slti        $a2, $a2, 0x0
    /* 107578 8130F3E8 38C60001 */  xori        $a2, $a2, 0x1
    /* 10757C 8130F3EC 8FA4006C */  lw          $a0, 0x6C($sp)
    /* 107580 8130F3F0 26050004 */  addiu       $a1, $s0, 0x4
    /* 107584 8130F3F4 87A70040 */  lh          $a3, 0x40($sp)
    /* 107588 8130F3F8 AFAA0010 */  sw          $t2, 0x10($sp)
    /* 10758C 8130F3FC AFAB0014 */  sw          $t3, 0x14($sp)
    /* 107590 8130F400 0C58028D */  jal         func_81600A34
    /* 107594 8130F404 AFAC0018 */   sw         $t4, 0x18($sp)
    /* 107598 8130F408 02002025 */  or          $a0, $s0, $zero
    /* 10759C 8130F40C 0C4C3426 */  jal         func_8130D098
    /* 1075A0 8130F410 27A50048 */   addiu      $a1, $sp, 0x48
    /* 1075A4 8130F414 87AD004A */  lh          $t5, 0x4A($sp)
    /* 1075A8 8130F418 87AE004C */  lh          $t6, 0x4C($sp)
    /* 1075AC 8130F41C 87AF004E */  lh          $t7, 0x4E($sp)
    /* 1075B0 8130F420 8FA4006C */  lw          $a0, 0x6C($sp)
    /* 1075B4 8130F424 26050003 */  addiu       $a1, $s0, 0x3
    /* 1075B8 8130F428 24060001 */  addiu       $a2, $zero, 0x1
    /* 1075BC 8130F42C 87A70048 */  lh          $a3, 0x48($sp)
    /* 1075C0 8130F430 AFAD0010 */  sw          $t5, 0x10($sp)
    /* 1075C4 8130F434 AFAE0014 */  sw          $t6, 0x14($sp)
    /* 1075C8 8130F438 0C58028D */  jal         func_81600A34
    /* 1075CC 8130F43C AFAF0018 */   sw         $t7, 0x18($sp)
    /* 1075D0 8130F440 02002025 */  or          $a0, $s0, $zero
    /* 1075D4 8130F444 0C4C347F */  jal         func_8130D1FC
    /* 1075D8 8130F448 27A50050 */   addiu      $a1, $sp, 0x50
    /* 1075DC 8130F44C 92060034 */  lbu         $a2, 0x34($s0)
    /* 1075E0 8130F450 87B80052 */  lh          $t8, 0x52($sp)
    /* 1075E4 8130F454 87B90054 */  lh          $t9, 0x54($sp)
    /* 1075E8 8130F458 87A80056 */  lh          $t0, 0x56($sp)
    /* 1075EC 8130F45C 38C60001 */  xori        $a2, $a2, 0x1
    /* 1075F0 8130F460 2CC60001 */  sltiu       $a2, $a2, 0x1
    /* 1075F4 8130F464 8FA4006C */  lw          $a0, 0x6C($sp)
    /* 1075F8 8130F468 26050001 */  addiu       $a1, $s0, 0x1
    /* 1075FC 8130F46C 87A70050 */  lh          $a3, 0x50($sp)
    /* 107600 8130F470 AFB80010 */  sw          $t8, 0x10($sp)
    /* 107604 8130F474 AFB90014 */  sw          $t9, 0x14($sp)
    /* 107608 8130F478 0C58028D */  jal         func_81600A34
    /* 10760C 8130F47C AFA80018 */   sw         $t0, 0x18($sp)
    /* 107610 8130F480 92090034 */  lbu         $t1, 0x34($s0)
    /* 107614 8130F484 02002025 */  or          $a0, $s0, $zero
    /* 107618 8130F488 29210005 */  slti        $at, $t1, 0x5
    /* 10761C 8130F48C 5420000F */  bnel        $at, $zero, .L8130F4CC
    /* 107620 8130F490 8E030070 */   lw         $v1, 0x70($s0)
    /* 107624 8130F494 0C4C34D0 */  jal         func_8130D340
    /* 107628 8130F498 27A50038 */   addiu      $a1, $sp, 0x38
    /* 10762C 8130F49C 87AA003A */  lh          $t2, 0x3A($sp)
    /* 107630 8130F4A0 87AB003C */  lh          $t3, 0x3C($sp)
    /* 107634 8130F4A4 87AC003E */  lh          $t4, 0x3E($sp)
    /* 107638 8130F4A8 8FA4006C */  lw          $a0, 0x6C($sp)
    /* 10763C 8130F4AC 26050002 */  addiu       $a1, $s0, 0x2
    /* 107640 8130F4B0 24060001 */  addiu       $a2, $zero, 0x1
    /* 107644 8130F4B4 87A70038 */  lh          $a3, 0x38($sp)
    /* 107648 8130F4B8 AFAA0010 */  sw          $t2, 0x10($sp)
    /* 10764C 8130F4BC AFAB0014 */  sw          $t3, 0x14($sp)
    /* 107650 8130F4C0 0C58028D */  jal         func_81600A34
    /* 107654 8130F4C4 AFAC0018 */   sw         $t4, 0x18($sp)
    /* 107658 8130F4C8 8E030070 */  lw          $v1, 0x70($s0)
  .L8130F4CC:
    /* 10765C 8130F4CC 10600008 */  beqz        $v1, .L8130F4F0
    /* 107660 8130F4D0 246DFFFF */   addiu      $t5, $v1, -0x1
    /* 107664 8130F4D4 AE0D0070 */  sw          $t5, 0x70($s0)
    /* 107668 8130F4D8 15A00005 */  bnez        $t5, .L8130F4F0
    /* 10766C 8130F4DC 01A01825 */   or         $v1, $t5, $zero
    /* 107670 8130F4E0 8E040068 */  lw          $a0, 0x68($s0)
    /* 107674 8130F4E4 0C010BE5 */  jal         func_80042F94
    /* 107678 8130F4E8 8E05006C */   lw         $a1, 0x6C($s0)
    /* 10767C 8130F4EC 8E030070 */  lw          $v1, 0x70($s0)
  .L8130F4F0:
    /* 107680 8130F4F0 5460001D */  bnel        $v1, $zero, .L8130F568
    /* 107684 8130F4F4 8FBF002C */   lw         $ra, 0x2C($sp)
    /* 107688 8130F4F8 920E0034 */  lbu         $t6, 0x34($s0)
    /* 10768C 8130F4FC 25CFFFFF */  addiu       $t7, $t6, -0x1
    /* 107690 8130F500 2DE10007 */  sltiu       $at, $t7, 0x7
    /* 107694 8130F504 10200017 */  beqz        $at, .L8130F564
    /* 107698 8130F508 000F7880 */   sll        $t7, $t7, 2
    /* 10769C 8130F50C 3C018131 */  lui         $at, %hi(jtbl_81312840)
    /* 1076A0 8130F510 002F0821 */  addu        $at, $at, $t7
    /* 1076A4 8130F514 8C2F2840 */  lw          $t7, %lo(jtbl_81312840)($at)
    /* 1076A8 8130F518 01E00008 */  jr          $t7
    /* 1076AC 8130F51C 00000000 */   nop
  jlabel .L8130F520
    /* 1076B0 8130F520 8E180068 */  lw          $t8, 0x68($s0)
    /* 1076B4 8130F524 53000010 */  beql        $t8, $zero, .L8130F568
    /* 1076B8 8130F528 8FBF002C */   lw         $ra, 0x2C($sp)
    /* 1076BC 8130F52C 0C5824BF */  jal         func_816092FC
    /* 1076C0 8130F530 00000000 */   nop
    /* 1076C4 8130F534 3C014700 */  lui         $at, (0x47000000 >> 16)
    /* 1076C8 8130F538 44812000 */  mtc1        $at, $ft0
    /* 1076CC 8130F53C 8E190068 */  lw          $t9, 0x68($s0)
    /* 1076D0 8130F540 46040182 */  mul.s       $ft1, $fv0, $ft0
    /* 1076D4 8130F544 8F24001C */  lw          $a0, 0x1C($t9)
    /* 1076D8 8130F548 4600320D */  trunc.w.s   $ft2, $ft1
    /* 1076DC 8130F54C 44054000 */  mfc1        $a1, $ft2
    /* 1076E0 8130F550 0C00FADD */  jal         ModelAnim_SetSpeed
    /* 1076E4 8130F554 00000000 */   nop
    /* 1076E8 8130F558 0C010D9E */  jal         func_80043678
    /* 1076EC 8130F55C 8E040068 */   lw         $a0, 0x68($s0)
    /* 1076F0 8130F560 AE020060 */  sw          $v0, 0x60($s0)
  jlabel .L8130F564
    /* 1076F4 8130F564 8FBF002C */  lw          $ra, 0x2C($sp)
  .L8130F568:
    /* 1076F8 8130F568 8FB00028 */  lw          $s0, 0x28($sp)
    /* 1076FC 8130F56C 27BD0068 */  addiu       $sp, $sp, 0x68
    /* 107700 8130F570 03E00008 */  jr          $ra
    /* 107704 8130F574 00000000 */   nop
