# Hand-maintained wrapper around func_82203E70's still-GLOBAL_ASM body.
# NOT auto-regenerated by `make extract` (splat only ever emits
# func_82203E70.s at this address, never this filename), so it's safe to
# carry the extra .late_rodata word below across re-extracts. See the
# comment on the GLOBAL_ASM pragma in fragment17_10FFC0.c for why this word
# lives here instead of as a plain C global.

.late_rodata
dlabel jtbl_8220E10C
.word 0x82203E9C

.text
glabel func_82203E70
    /* 113830 82203E70 27BDFFE0 */  addiu       $sp, $sp, -0x20
    /* 113834 82203E74 2C810005 */  sltiu       $at, $a0, 0x5
    /* 113838 82203E78 AFBF0014 */  sw          $ra, 0x14($sp)
    /* 11383C 82203E7C 10200066 */  beqz        $at, .L82204018
    /* 113840 82203E80 AFA40018 */   sw         $a0, 0x18($sp)
    /* 113844 82203E84 00047080 */  sll         $t6, $a0, 2
    /* 113848 82203E88 3C018221 */  lui         $at, %hi(jtbl_8220E10C)
    /* 11384C 82203E8C 002E0821 */  addu        $at, $at, $t6
    /* 113850 82203E90 8C2EE10C */  lw          $t6, %lo(jtbl_8220E10C)($at)
    /* 113854 82203E94 01C00008 */  jr          $t6
    /* 113858 82203E98 00000000 */   nop
  jlabel .L82203E9C
    /* 11385C 82203E9C 0C002128 */  jal         StageContext_GetFadeMode
    /* 113860 82203EA0 00000000 */   nop
    /* 113864 82203EA4 14400006 */  bnez        $v0, .L82203EC0
    /* 113868 82203EA8 3C198221 */   lui        $t9, %hi(D_8220D84C)
    /* 11386C 82203EAC 3C0F8221 */  lui         $t7, %hi(D_8220D84C)
    /* 113870 82203EB0 8DEFD84C */  lw          $t7, %lo(D_8220D84C)($t7)
    /* 113874 82203EB4 3C018221 */  lui         $at, %hi(D_8220D84C)
    /* 113878 82203EB8 25F80001 */  addiu       $t8, $t7, 0x1
    /* 11387C 82203EBC AC38D84C */  sw          $t8, %lo(D_8220D84C)($at)
  .L82203EC0:
    /* 113880 82203EC0 8F39D84C */  lw          $t9, %lo(D_8220D84C)($t9)
    /* 113884 82203EC4 24080001 */  addiu       $t0, $zero, 0x1
    /* 113888 82203EC8 2B210002 */  slti        $at, $t9, 0x2
    /* 11388C 82203ECC 54200053 */  bnel        $at, $zero, .L8220401C
    /* 113890 82203ED0 8FBF0014 */   lw         $ra, 0x14($sp)
    /* 113894 82203ED4 0C880EA1 */  jal         func_82203A84
    /* 113898 82203ED8 AFA80018 */   sw         $t0, 0x18($sp)
    /* 11389C 82203EDC 3C018221 */  lui         $at, %hi(D_8220D84C)
    /* 1138A0 82203EE0 1000004D */  b           .L82204018
    /* 1138A4 82203EE4 AC20D84C */   sw         $zero, %lo(D_8220D84C)($at)
  jlabel .L82203EE8
    /* 1138A8 82203EE8 3C048221 */  lui         $a0, %hi(D_8220D850)
    /* 1138AC 82203EEC 3C058221 */  lui         $a1, %hi(D_8220D858)
    /* 1138B0 82203EF0 8CA5D858 */  lw          $a1, %lo(D_8220D858)($a1)
    /* 1138B4 82203EF4 8C84D850 */  lw          $a0, %lo(D_8220D850)($a0)
    /* 1138B8 82203EF8 3C0A8221 */  lui         $t2, %hi(D_8220D854)
    /* 1138BC 82203EFC 3C0C8221 */  lui         $t4, %hi(D_8220D85C)
    /* 1138C0 82203F00 8D8CD85C */  lw          $t4, %lo(D_8220D85C)($t4)
    /* 1138C4 82203F04 8D4AD854 */  lw          $t2, %lo(D_8220D854)($t2)
    /* 1138C8 82203F08 00055823 */  negu        $t3, $a1
    /* 1138CC 82203F0C 00044823 */  negu        $t1, $a0
    /* 1138D0 82203F10 016C3823 */  subu        $a3, $t3, $t4
    /* 1138D4 82203F14 012A3023 */  subu        $a2, $t1, $t2
    /* 1138D8 82203F18 24C60280 */  addiu       $a2, $a2, 0x280
    /* 1138DC 82203F1C 0C88053F */  jal         func_822014FC
    /* 1138E0 82203F20 24E701E0 */   addiu      $a3, $a3, 0x1E0
    /* 1138E4 82203F24 0C880EA6 */  jal         func_82203A98
    /* 1138E8 82203F28 00000000 */   nop
    /* 1138EC 82203F2C 1040003A */  beqz        $v0, .L82204018
    /* 1138F0 82203F30 3C028221 */   lui        $v0, %hi(D_8220E4C0)
    /* 1138F4 82203F34 2442E4C0 */  addiu       $v0, $v0, %lo(D_8220E4C0)
    /* 1138F8 82203F38 944E0000 */  lhu         $t6, 0x0($v0)
    /* 1138FC 82203F3C 240D0002 */  addiu       $t5, $zero, 0x2
    /* 113900 82203F40 AFAD0018 */  sw          $t5, 0x18($sp)
    /* 113904 82203F44 35CF0004 */  ori         $t7, $t6, 0x4
    /* 113908 82203F48 10000033 */  b           .L82204018
    /* 11390C 82203F4C A44F0000 */   sh         $t7, 0x0($v0)
  jlabel .L82203F50
    /* 113910 82203F50 0C880ECF */  jal         func_82203B3C
    /* 113914 82203F54 00000000 */   nop
    /* 113918 82203F58 2401FFFF */  addiu       $at, $zero, -0x1
    /* 11391C 82203F5C 14410006 */  bne         $v0, $at, .L82203F78
    /* 113920 82203F60 AFA2001C */   sw         $v0, 0x1C($sp)
    /* 113924 82203F64 24180004 */  addiu       $t8, $zero, 0x4
    /* 113928 82203F68 0C880F90 */  jal         func_82203E40
    /* 11392C 82203F6C AFB80018 */   sw         $t8, 0x18($sp)
    /* 113930 82203F70 10000015 */  b           .L82203FC8
    /* 113934 82203F74 8FAF001C */   lw         $t7, 0x1C($sp)
  .L82203F78:
    /* 113938 82203F78 24010001 */  addiu       $at, $zero, 0x1
    /* 11393C 82203F7C 14410011 */  bne         $v0, $at, .L82203FC4
    /* 113940 82203F80 24190003 */   addiu      $t9, $zero, 0x3
    /* 113944 82203F84 3C088221 */  lui         $t0, %hi(D_8220E360)
    /* 113948 82203F88 8D08E360 */  lw          $t0, %lo(D_8220E360)($t0)
    /* 11394C 82203F8C AFB90018 */  sw          $t9, 0x18($sp)
    /* 113950 82203F90 0C880536 */  jal         func_822014D8
    /* 113954 82203F94 AD000000 */   sw         $zero, 0x0($t0)
    /* 113958 82203F98 0C880EE6 */  jal         func_82203B98
    /* 11395C 82203F9C 00000000 */   nop
    /* 113960 82203FA0 3C028221 */  lui         $v0, %hi(D_8220E4C0)
    /* 113964 82203FA4 2442E4C0 */  addiu       $v0, $v0, %lo(D_8220E4C0)
    /* 113968 82203FA8 94490000 */  lhu         $t1, 0x0($v0)
    /* 11396C 82203FAC 312BFFFE */  andi        $t3, $t1, 0xFFFE
    /* 113970 82203FB0 316DFFFD */  andi        $t5, $t3, 0xFFFD
    /* 113974 82203FB4 A44B0000 */  sh          $t3, 0x0($v0)
    /* 113978 82203FB8 A44D0000 */  sh          $t5, 0x0($v0)
    /* 11397C 82203FBC 31AEFFF7 */  andi        $t6, $t5, 0xFFF7
    /* 113980 82203FC0 A44E0000 */  sh          $t6, 0x0($v0)
  .L82203FC4:
    /* 113984 82203FC4 8FAF001C */  lw          $t7, 0x1C($sp)
  .L82203FC8:
    /* 113988 82203FC8 3C028221 */  lui         $v0, %hi(D_8220E4C0)
    /* 11398C 82203FCC 2442E4C0 */  addiu       $v0, $v0, %lo(D_8220E4C0)
    /* 113990 82203FD0 51E00012 */  beql        $t7, $zero, .L8220401C
    /* 113994 82203FD4 8FBF0014 */   lw         $ra, 0x14($sp)
    /* 113998 82203FD8 94580000 */  lhu         $t8, 0x0($v0)
    /* 11399C 82203FDC 3319FFFB */  andi        $t9, $t8, 0xFFFB
    /* 1139A0 82203FE0 1000000D */  b           .L82204018
    /* 1139A4 82203FE4 A4590000 */   sh         $t9, 0x0($v0)
  jlabel .L82203FE8
    /* 1139A8 82203FE8 0C880EF6 */  jal         func_82203BD8
    /* 1139AC 82203FEC 00000000 */   nop
    /* 1139B0 82203FF0 10400009 */  beqz        $v0, .L82204018
    /* 1139B4 82203FF4 24080005 */   addiu      $t0, $zero, 0x5
    /* 1139B8 82203FF8 10000007 */  b           .L82204018
    /* 1139BC 82203FFC AFA80018 */   sw         $t0, 0x18($sp)
  jlabel .L82204000
    /* 1139C0 82204000 0C002128 */  jal         StageContext_GetFadeMode
    /* 1139C4 82204004 00000000 */   nop
    /* 1139C8 82204008 24010001 */  addiu       $at, $zero, 0x1
    /* 1139CC 8220400C 14410002 */  bne         $v0, $at, .L82204018
    /* 1139D0 82204010 24090005 */   addiu      $t1, $zero, 0x5
    /* 1139D4 82204014 AFA90018 */  sw          $t1, 0x18($sp)
  .L82204018:
    /* 1139D8 82204018 8FBF0014 */  lw          $ra, 0x14($sp)
  .L8220401C:
    /* 1139DC 8220401C 8FA20018 */  lw          $v0, 0x18($sp)
    /* 1139E0 82204020 27BD0020 */  addiu       $sp, $sp, 0x20
    /* 1139E4 82204024 03E00008 */  jr          $ra
    /* 1139E8 82204028 00000000 */   nop
