.section .text
/* Generated by spimdisasm 1.35.0-dev0 */

glabel func_8002A9D8
    /* 02B5D8 8002A9D8 27BDFFC0 */  addiu       $sp, $sp, -0x40
    /* 02B5DC 8002A9DC AFB70034 */  sw          $s7, 0x34($sp)
    /* 02B5E0 8002A9E0 AFB60030 */  sw          $s6, 0x30($sp)
    /* 02B5E4 8002A9E4 AFB5002C */  sw          $s5, 0x2C($sp)
    /* 02B5E8 8002A9E8 AFB40028 */  sw          $s4, 0x28($sp)
    /* 02B5EC 8002A9EC AFB30024 */  sw          $s3, 0x24($sp)
    /* 02B5F0 8002A9F0 AFB20020 */  sw          $s2, 0x20($sp)
    /* 02B5F4 8002A9F4 AFB00018 */  sw          $s0, 0x18($sp)
    /* 02B5F8 8002A9F8 AFBE0038 */  sw          $fp, 0x38($sp)
    /* 02B5FC 8002A9FC AFB1001C */  sw          $s1, 0x1C($sp)
    /* 02B600 8002AA00 3C10800D */  lui         $s0, %hi(D_800D1B80)
    /* 02B604 8002AA04 3C12800D */  lui         $s2, %hi(D_800D1B78)
    /* 02B608 8002AA08 3C13800A */  lui         $s3, %hi(D_800A3A60)
    /* 02B60C 8002AA0C 3C14800A */  lui         $s4, %hi(D_800A3A6C)
    /* 02B610 8002AA10 3C15800A */  lui         $s5, %hi(D_800A3A84)
    /* 02B614 8002AA14 3C16800A */  lui         $s6, %hi(D_800A3A94)
    /* 02B618 8002AA18 3C17800A */  lui         $s7, %hi(D_800A3AA4)
    /* 02B61C 8002AA1C AFBF003C */  sw          $ra, 0x3C($sp)
    /* 02B620 8002AA20 26F73AA4 */  addiu       $s7, $s7, %lo(D_800A3AA4)
    /* 02B624 8002AA24 26D63A94 */  addiu       $s6, $s6, %lo(D_800A3A94)
    /* 02B628 8002AA28 26B53A84 */  addiu       $s5, $s5, %lo(D_800A3A84)
    /* 02B62C 8002AA2C 26943A6C */  addiu       $s4, $s4, %lo(D_800A3A6C)
    /* 02B630 8002AA30 26733A60 */  addiu       $s3, $s3, %lo(D_800A3A60)
    /* 02B634 8002AA34 26521B78 */  addiu       $s2, $s2, %lo(D_800D1B78)
    /* 02B638 8002AA38 26101B80 */  addiu       $s0, $s0, %lo(D_800D1B80)
    /* 02B63C 8002AA3C 00008825 */  or          $s1, $zero, $zero
    /* 02B640 8002AA40 241E0002 */  addiu       $fp, $zero, 0x2
  .L8002AA44:
    /* 02B644 8002AA44 02602025 */  or          $a0, $s3, $zero
    /* 02B648 8002AA48 0C01EFF7 */  jal         osSyncPrintf
    /* 02B64C 8002AA4C 02202825 */   or         $a1, $s1, $zero
    /* 02B650 8002AA50 8E4E0000 */  lw          $t6, 0x0($s2)
    /* 02B654 8002AA54 02802025 */  or          $a0, $s4, $zero
    /* 02B658 8002AA58 0C01EFF7 */  jal         osSyncPrintf
    /* 02B65C 8002AA5C 91C50001 */   lbu        $a1, 0x1($t6)
    /* 02B660 8002AA60 8E0F0000 */  lw          $t7, 0x0($s0)
    /* 02B664 8002AA64 02A02025 */  or          $a0, $s5, $zero
    /* 02B668 8002AA68 0C01EFF7 */  jal         osSyncPrintf
    /* 02B66C 8002AA6C 91E50000 */   lbu        $a1, 0x0($t7)
    /* 02B670 8002AA70 8E180000 */  lw          $t8, 0x0($s0)
    /* 02B674 8002AA74 02C02025 */  or          $a0, $s6, $zero
    /* 02B678 8002AA78 0C01EFF7 */  jal         osSyncPrintf
    /* 02B67C 8002AA7C 93050003 */   lbu        $a1, 0x3($t8)
    /* 02B680 8002AA80 8E190000 */  lw          $t9, 0x0($s0)
    /* 02B684 8002AA84 02E02025 */  or          $a0, $s7, $zero
    /* 02B688 8002AA88 0C01EFF7 */  jal         osSyncPrintf
    /* 02B68C 8002AA8C 93250004 */   lbu        $a1, 0x4($t9)
    /* 02B690 8002AA90 26310001 */  addiu       $s1, $s1, 0x1
    /* 02B694 8002AA94 26520004 */  addiu       $s2, $s2, 0x4
    /* 02B698 8002AA98 163EFFEA */  bne         $s1, $fp, .L8002AA44
    /* 02B69C 8002AA9C 26100004 */   addiu      $s0, $s0, 0x4
    /* 02B6A0 8002AAA0 8FBF003C */  lw          $ra, 0x3C($sp)
    /* 02B6A4 8002AAA4 8FB00018 */  lw          $s0, 0x18($sp)
    /* 02B6A8 8002AAA8 8FB1001C */  lw          $s1, 0x1C($sp)
    /* 02B6AC 8002AAAC 8FB20020 */  lw          $s2, 0x20($sp)
    /* 02B6B0 8002AAB0 8FB30024 */  lw          $s3, 0x24($sp)
    /* 02B6B4 8002AAB4 8FB40028 */  lw          $s4, 0x28($sp)
    /* 02B6B8 8002AAB8 8FB5002C */  lw          $s5, 0x2C($sp)
    /* 02B6BC 8002AABC AFB60030 */  lw          $s6, 0x30($sp)
    /* 02B6C0 8002AAC0 8FB70034 */  lw          $s7, 0x34($sp)
    /* 02B6C4 8002AAC4 8FBE0038 */  lw          $fp, 0x38($sp)
    /* 02B6C8 8002AAC8 03E00008 */  jr          $ra
    /* 02B6CC 8002AACC 27BD0040 */   addiu      $sp, $sp, 0x40
