.section .late_rodata
.align 2
dlabel D_800A3990
    .word 0x080f120c, 0x080b0d06, 0x1a0c0c07, 0x19000000
.align 2

dlabel D_800A39A0
    .word 0x25660A00
.align 2

dlabel D_800A39A4
    .word 0x25326420, 0x3A202533, 0x640A0000
.align 2

.section .text
/* Generated by spimdisasm 1.35.0-dev0 */

glabel func_80026BB4
    /* 0277B4 80026BB4 27BDFFD8 */  addiu       $sp, $sp, -0x28
    /* 0277B8 80026BB8 AFB00014 */  sw          $s0, 0x14($sp)
    /* 0277BC 80026BBC AFB2001C */  sw          $s2, 0x1C($sp)
    /* 0277C0 80026BC0 3C10800D */  lui         $s0, %hi(D_800D19A0)
    /* 0277C4 80026BC4 3C02800D */  lui         $v0, %hi(D_800D1A68)
    /* 0277C8 80026BC8 309200FF */  andi        $s2, $a0, 0xFF
    /* 0277CC 80026BCC AFBF0024 */  sw          $ra, 0x24($sp)
    /* 0277D0 80026BD0 AFB30020 */  sw          $s3, 0x20($sp)
    /* 0277D4 80026BD4 AFB10018 */  sw          $s1, 0x18($sp)
    /* 0277D8 80026BD8 AFA40028 */  sw          $a0, 0x28($sp)
    /* 0277DC 80026BDC 24421A68 */  addiu       $v0, $v0, %lo(D_800D1A68)
    /* 0277E0 80026BE0 261019A0 */  addiu       $s0, $s0, %lo(D_800D19A0)
  .L80026BE4:
    /* 0277E4 80026BE4 26100002 */  addiu       $s0, $s0, 0x2
    /* 0277E8 80026BE8 0202082B */  sltu        $at, $s0, $v0
    /* 0277EC 80026BEC 1420FFFD */  bnez        $at, .L80026BE4
    /* 0277F0 80026BF0 A600FFFE */   sh         $zero, -0x2($s0)
    /* 0277F4 80026BF4 3C10800A */  lui         $s0, %hi(D_800A39A0)
    /* 0277F8 80026BF8 261039A0 */  addiu       $s0, $s0, %lo(D_800A39A0)
    /* 0277FC 80026BFC 00008825 */  or          $s1, $zero, $zero
  .L80026C00:
    /* 027800 80026C00 0C009A64 */  jal         func_80026990
    /* 027804 80026C04 324400FF */   andi       $a0, $s2, 0xFF
    /* 027808 80026C08 46000121 */  cvt.d.s     $ft0, $fv0
    /* 02780C 80026C0C 02002025 */  or          $a0, $s0, $zero
    /* 027810 80026C10 44072000 */  mfc1        $a3, $ft0
    /* 027814 80026C14 44062800 */  mfc1        $a2, $ft0f
    /* 027818 80026C18 0C01EFF7 */  jal         osSyncPrintf
    /* 02781C 80026C1C 00000000 */   nop
    /* 027820 80026C20 26310001 */  addiu       $s1, $s1, 0x1
    /* 027824 80026C24 2A2103E8 */  slti        $at, $s1, 0x3E8
    /* 027828 80026C28 1420FFF5 */  bnez        $at, .L80026C00
    /* 02782C 80026C2C 00000000 */   nop
    /* 027830 80026C30 3C10800D */  lui         $s0, %hi(D_800D19A0)
    /* 027834 80026C34 3C12800A */  lui         $s2, %hi(D_800A39A4)
    /* 027838 80026C38 265239A4 */  addiu       $s2, $s2, %lo(D_800A39A4)
    /* 02783C 80026C3C 261019A0 */  addiu       $s0, $s0, %lo(D_800D19A0)
    /* 027840 80026C40 00008825 */  or          $s1, $zero, $zero
    /* 027844 80026C44 24130064 */  addiu       $s3, $zero, 0x64
  .L80026C48:
    /* 027848 80026C48 02402025 */  or          $a0, $s2, $zero
    /* 02784C 80026C4C 02202825 */  or          $a1, $s1, $zero
    /* 027850 80026C50 0C01EFF7 */  jal         osSyncPrintf
    /* 027854 80026C54 96060000 */   lhu        $a2, 0x0($s0)
    /* 027858 80026C58 26310001 */  addiu       $s1, $s1, 0x1
    /* 02785C 80026C5C 1633FFFA */  bne         $s1, $s3, .L80026C48
    /* 027860 80026C60 26100002 */   addiu      $s0, $s0, 0x2
    /* 027864 80026C64 8FBF0024 */  lw          $ra, 0x24($sp)
    /* 027868 80026C68 8FB00014 */  lw          $s0, 0x14($sp)
    /* 02786C 80026C6C 8FB10018 */  lw          $s1, 0x18($sp)
    /* 027870 80026C70 8FB2001C */  lw          $s2, 0x1C($sp)
    /* 027874 80026C74 8FB30020 */  lw          $s3, 0x20($sp)
    /* 027878 80026C78 03E00008 */  jr          $ra
    /* 02787C 80026C7C 27BD0028 */   addiu      $sp, $sp, 0x28
