# Hand-maintained wrapper around func_80024F20's still-GLOBAL_ASM body.
# NOT auto-regenerated by `make extract` (splat only ever emits
# func_80024F20.s at this address, never this filename), so it's safe to
# carry the extra .late_rodata padding below across re-extracts.
#
# The 3 extra zero words below are retail padding that sits right after
# func_80024E8C's own compiler-generated switch table (jtbl_800A3280, 13
# entries = 0x34 bytes) to align jtbl_800A32C0 (this function's own table,
# right below) to its real retail address 0x800A32C0. A plain C global here
# would instead be emitted by IDO BEFORE func_80024E8C's switch table (IDO
# always emits named/array rodata ahead of switch-table "late" rodata
# within one compilation), landing at the wrong address -- see the
# analogous func_82203E70_manual.s precedent in
# hand_asm/fragments/17/func_82203E70_manual.s. Placing it in a GLOBAL_ASM
# .late_rodata block instead makes asm-processor position it correctly,
# matching retail.

.late_rodata
.word 0
.word 0
.word 0
dlabel jtbl_800A32C0
    /* 0A3EC0 800A32C0 8002519C */ .word .L8002519C
    /* 0A3EC4 800A32C4 800251AC */ .word .L800251AC
    /* 0A3EC8 800A32C8 800251AC */ .word .L800251AC
    /* 0A3ECC 800A32CC 800251AC */ .word .L800251AC
    /* 0A3ED0 800A32D0 8002519C */ .word .L8002519C
    /* 0A3ED4 800A32D4 800251AC */ .word .L800251AC
    /* 0A3ED8 800A32D8 800251AC */ .word .L800251AC
    /* 0A3EDC 800A32DC 800251AC */ .word .L800251AC
    /* 0A3EE0 800A32E0 800251AC */ .word .L800251AC
    /* 0A3EE4 800A32E4 800251AC */ .word .L800251AC
    /* 0A3EE8 800A32E8 800251AC */ .word .L800251AC
    /* 0A3EEC 800A32EC 800251A4 */ .word .L800251A4
    /* 0A3EF0 800A32F0 800251A4 */ .word .L800251A4
    /* 0A3EF4 800A32F4 800251AC */ .word .L800251AC
    /* 0A3EF8 800A32F8 8002519C */ .word .L8002519C
    /* 0A3EFC 800A32FC 8002519C */ .word .L8002519C

.text
glabel func_80024F20
    /* 025B20 80024F20 27BDFFC8 */  addiu       $sp, $sp, -0x38
    /* 025B24 80024F24 AFB00018 */  sw          $s0, 0x18($sp)
    /* 025B28 80024F28 3C020001 */  lui         $v0, (0x10005 >> 16)
    /* 025B2C 80024F2C 34420005 */  ori         $v0, $v0, (0x10005 & 0xFFFF)
    /* 025B30 80024F30 00808025 */  or          $s0, $a0, $zero
    /* 025B34 80024F34 AFBF001C */  sw          $ra, 0x1C($sp)
    /* 025B38 80024F38 00A03825 */  or          $a3, $a1, $zero
  .L80024F3C:
    /* 025B3C 80024F3C 24010064 */  addiu       $at, $zero, 0x64
    /* 025B40 80024F40 1201000B */  beq         $s0, $at, .L80024F70
    /* 025B44 80024F44 3C0E8009 */   lui        $t6, %hi(D_80090A9C)
    /* 025B48 80024F48 24010065 */  addiu       $at, $zero, 0x65
    /* 025B4C 80024F4C 1201002C */  beq         $s0, $at, .L80025000
    /* 025B50 80024F50 3C040001 */   lui        $a0, (0x10001 >> 16)
    /* 025B54 80024F54 24010066 */  addiu       $at, $zero, 0x66
    /* 025B58 80024F58 12010051 */  beq         $s0, $at, .L800250A0
    /* 025B5C 80024F5C 3C040604 */   lui        $a0, (0x6040405 >> 16)
    /* 025B60 80024F60 1202004D */  beq         $s0, $v0, .L80025098
    /* 025B64 80024F64 3C018009 */   lui        $at, %hi(D_80090A9C)
    /* 025B68 80024F68 1000005C */  b           .L800250DC
    /* 025B6C 80024F6C 3C01FFFF */   lui        $at, (0xFFFF0000 >> 16)
  .L80024F70:
    /* 025B70 80024F70 10E0001C */  beqz        $a3, .L80024FE4
    /* 025B74 80024F74 3C040001 */   lui        $a0, (0x1000A >> 16)
    /* 025B78 80024F78 24010001 */  addiu       $at, $zero, 0x1
    /* 025B7C 80024F7C 10E10013 */  beq         $a3, $at, .L80024FCC
    /* 025B80 80024F80 3C040001 */   lui        $a0, (0x10009 >> 16)
    /* 025B84 80024F84 24010002 */  addiu       $at, $zero, 0x2
    /* 025B88 80024F88 10E1000A */  beq         $a3, $at, .L80024FB4
    /* 025B8C 80024F8C 3C040001 */   lui        $a0, (0x10008 >> 16)
    /* 025B90 80024F90 24010003 */  addiu       $at, $zero, 0x3
    /* 025B94 80024F94 14E10017 */  bne         $a3, $at, .L80024FF4
    /* 025B98 80024F98 3C040001 */   lui        $a0, (0x10007 >> 16)
    /* 025B9C 80024F9C 34840007 */  ori         $a0, $a0, (0x10007 & 0xFFFF)
    /* 025BA0 80024FA0 00002825 */  or          $a1, $zero, $zero
    /* 025BA4 80024FA4 0C0093C8 */  jal         func_80024F20
    /* 025BA8 80024FA8 00003025 */   or         $a2, $zero, $zero
    /* 025BAC 80024FAC 10000011 */  b           .L80024FF4
    /* 025BB0 80024FB0 00000000 */   nop
  .L80024FB4:
    /* 025BB4 80024FB4 34840008 */  ori         $a0, $a0, (0x10008 & 0xFFFF)
    /* 025BB8 80024FB8 00002825 */  or          $a1, $zero, $zero
    /* 025BBC 80024FBC 0C0093C8 */  jal         func_80024F20
    /* 025BC0 80024FC0 00003025 */   or         $a2, $zero, $zero
    /* 025BC4 80024FC4 1000000B */  b           .L80024FF4
    /* 025BC8 80024FC8 00000000 */   nop
  .L80024FCC:
    /* 025BCC 80024FCC 34840009 */  ori         $a0, $a0, (0x10009 & 0xFFFF)
    /* 025BD0 80024FD0 00002825 */  or          $a1, $zero, $zero
    /* 025BD4 80024FD4 0C0093C8 */  jal         func_80024F20
    /* 025BD8 80024FD8 00003025 */   or         $a2, $zero, $zero
    /* 025BDC 80024FDC 10000005 */  b           .L80024FF4
    /* 025BE0 80024FE0 00000000 */   nop
  .L80024FE4:
    /* 025BE4 80024FE4 3484000A */  ori         $a0, $a0, (0x1000A & 0xFFFF)
    /* 025BE8 80024FE8 00002825 */  or          $a1, $zero, $zero
    /* 025BEC 80024FEC 0C0093C8 */  jal         func_80024F20
    /* 025BF0 80024FF0 00003025 */   or         $a2, $zero, $zero
  .L80024FF4:
    /* 025BF4 80024FF4 3C018009 */  lui         $at, %hi(D_80090A9C)
    /* 025BF8 80024FF8 1000007A */  b           .L800251E4
    /* 025BFC 80024FFC A0200A9C */   sb         $zero, %lo(D_80090A9C)($at)
  .L80025000:
    /* 025C00 80025000 91CE0A9C */  lbu         $t6, %lo(D_80090A9C)($t6)
    /* 025C04 80025004 34840001 */  ori         $a0, $a0, (0x10001 & 0xFFFF)
    /* 025C08 80025008 00002825 */  or          $a1, $zero, $zero
    /* 025C0C 8002500C 15C00009 */  bnez        $t6, .L80025034
    /* 025C10 80025010 00003025 */   or         $a2, $zero, $zero
    /* 025C14 80025014 0C0093C8 */  jal         func_80024F20
    /* 025C18 80025018 AFA7003C */   sw         $a3, 0x3C($sp)
    /* 025C1C 8002501C 3C020001 */  lui         $v0, (0x10005 >> 16)
    /* 025C20 80025020 240F0001 */  addiu       $t7, $zero, 0x1
    /* 025C24 80025024 3C018009 */  lui         $at, %hi(D_80090A9C)
    /* 025C28 80025028 34420005 */  ori         $v0, $v0, (0x10005 & 0xFFFF)
    /* 025C2C 8002502C 8FA7003C */  lw          $a3, 0x3C($sp)
    /* 025C30 80025030 A02F0A9C */  sb          $t7, %lo(D_80090A9C)($at)
  .L80025034:
    /* 025C34 80025034 28E10006 */  slti        $at, $a3, 0x6
    /* 025C38 80025038 14200005 */  bnez        $at, .L80025050
    /* 025C3C 8002503C 3C100001 */   lui        $s0, (0x10002 >> 16)
    /* 025C40 80025040 36100002 */  ori         $s0, $s0, (0x10002 & 0xFFFF)
    /* 025C44 80025044 00003825 */  or          $a3, $zero, $zero
    /* 025C48 80025048 1000FFBC */  b           .L80024F3C
    /* 025C4C 8002504C 00003025 */   or         $a2, $zero, $zero
  .L80025050:
    /* 025C50 80025050 28E10003 */  slti        $at, $a3, 0x3
    /* 025C54 80025054 14200005 */  bnez        $at, .L8002506C
    /* 025C58 80025058 3C100001 */   lui        $s0, (0x10003 >> 16)
    /* 025C5C 8002505C 36100003 */  ori         $s0, $s0, (0x10003 & 0xFFFF)
    /* 025C60 80025060 00003825 */  or          $a3, $zero, $zero
    /* 025C64 80025064 1000FFB5 */  b           .L80024F3C
    /* 025C68 80025068 00003025 */   or         $a2, $zero, $zero
  .L8002506C:
    /* 025C6C 8002506C 18E00005 */  blez        $a3, .L80025084
    /* 025C70 80025070 3C100001 */   lui        $s0, (0x10004 >> 16)
    /* 025C74 80025074 36100004 */  ori         $s0, $s0, (0x10004 & 0xFFFF)
    /* 025C78 80025078 00003825 */  or          $a3, $zero, $zero
    /* 025C7C 8002507C 1000FFAF */  b           .L80024F3C
    /* 025C80 80025080 00003025 */   or         $a2, $zero, $zero
  .L80025084:
    /* 025C84 80025084 14E00057 */  bnez        $a3, .L800251E4
    /* 025C88 80025088 00408025 */   or         $s0, $v0, $zero
    /* 025C8C 8002508C 00003825 */  or          $a3, $zero, $zero
    /* 025C90 80025090 1000FFAA */  b           .L80024F3C
    /* 025C94 80025094 00003025 */   or         $a2, $zero, $zero
  .L80025098:
    /* 025C98 80025098 1000000F */  b           .L800250D8
    /* 025C9C 8002509C A0200A9C */   sb         $zero, %lo(D_80090A9C)($at)
  .L800250A0:
    /* 025CA0 800250A0 34840405 */  ori         $a0, $a0, (0x6040405 & 0xFFFF)
    /* 025CA4 800250A4 0C0061D3 */  jal         func_8001874C
    /* 025CA8 800250A8 24050001 */   addiu      $a1, $zero, 0x1
    /* 025CAC 800250AC 3C040604 */  lui         $a0, (0x6040505 >> 16)
    /* 025CB0 800250B0 34840505 */  ori         $a0, $a0, (0x6040505 & 0xFFFF)
    /* 025CB4 800250B4 0C0061D3 */  jal         func_8001874C
    /* 025CB8 800250B8 24050001 */   addiu      $a1, $zero, 0x1
    /* 025CBC 800250BC 3C040604 */  lui         $a0, (0x6040605 >> 16)
    /* 025CC0 800250C0 34840605 */  ori         $a0, $a0, (0x6040605 & 0xFFFF)
    /* 025CC4 800250C4 0C0061D3 */  jal         func_8001874C
    /* 025CC8 800250C8 24050001 */   addiu      $a1, $zero, 0x1
    /* 025CCC 800250CC 3C018009 */  lui         $at, %hi(D_80090A9C)
    /* 025CD0 800250D0 10000044 */  b           .L800251E4
    /* 025CD4 800250D4 A0200A9C */   sb         $zero, %lo(D_80090A9C)($at)
  .L800250D8:
    /* 025CD8 800250D8 3C01FFFF */  lui         $at, (0xFFFF0000 >> 16)
  .L800250DC:
    /* 025CDC 800250DC 02011024 */  and         $v0, $s0, $at
    /* 025CE0 800250E0 10400006 */  beqz        $v0, .L800250FC
    /* 025CE4 800250E4 28E10004 */   slti       $at, $a3, 0x4
    /* 025CE8 800250E8 3C010001 */  lui         $at, (0x10000 >> 16)
    /* 025CEC 800250EC 50410021 */  beql        $v0, $at, .L80025174
    /* 025CF0 800250F0 3C01FFFE */   lui        $at, (0xFFFEFFFF >> 16)
    /* 025CF4 800250F4 1000003C */  b           .L800251E8
    /* 025CF8 800250F8 8FBF001C */   lw         $ra, 0x1C($sp)
  .L800250FC:
    /* 025CFC 800250FC 5020003A */  beql        $at, $zero, .L800251E8
    /* 025D00 80025100 8FBF001C */   lw         $ra, 0x1C($sp)
    /* 025D04 80025104 04E00037 */  bltz        $a3, .L800251E4
    /* 025D08 80025108 24010004 */   addiu      $at, $zero, 0x4
    /* 025D0C 8002510C 14C10003 */  bne         $a2, $at, .L8002511C
    /* 025D10 80025110 3C088009 */   lui        $t0, %hi(D_80090A94)
    /* 025D14 80025114 10000002 */  b           .L80025120
    /* 025D18 80025118 24060001 */   addiu      $a2, $zero, 0x1
  .L8002511C:
    /* 025D1C 8002511C 00003025 */  or          $a2, $zero, $zero
  .L80025120:
    /* 025D20 80025120 0006C080 */  sll         $t8, $a2, 2
    /* 025D24 80025124 0307C821 */  addu        $t9, $t8, $a3
    /* 025D28 80025128 01194021 */  addu        $t0, $t0, $t9
    /* 025D2C 8002512C 30E400FF */  andi        $a0, $a3, 0xFF
    /* 025D30 80025130 91080A94 */  lbu         $t0, %lo(D_80090A94)($t0)
    /* 025D34 80025134 00042200 */  sll         $a0, $a0, 8
    /* 025D38 80025138 3C010604 */  lui         $at, (0x6040000 >> 16)
    /* 025D3C 8002513C 02002825 */  or          $a1, $s0, $zero
    /* 025D40 80025140 00052E00 */  sll         $a1, $a1, 24
    /* 025D44 80025144 00812025 */  or          $a0, $a0, $at
    /* 025D48 80025148 AFA40024 */  sw          $a0, 0x24($sp)
    /* 025D4C 8002514C 00052E03 */  sra         $a1, $a1, 24
    /* 025D50 80025150 0C0061D3 */  jal         func_8001874C
    /* 025D54 80025154 A3A80033 */   sb         $t0, 0x33($sp)
    /* 025D58 80025158 8FA40024 */  lw          $a0, 0x24($sp)
    /* 025D5C 8002515C 83A50033 */  lb          $a1, 0x33($sp)
    /* 025D60 80025160 0C0061D3 */  jal         func_8001874C
    /* 025D64 80025164 34840001 */   ori        $a0, $a0, 0x1
    /* 025D68 80025168 1000001F */  b           .L800251E8
    /* 025D6C 8002516C 8FBF001C */   lw         $ra, 0x1C($sp)
    /* 025D70 80025170 3C01FFFE */  lui         $at, (0xFFFEFFFF >> 16)
  .L80025174:
    /* 025D74 80025174 3421FFFF */  ori         $at, $at, (0xFFFEFFFF & 0xFFFF)
    /* 025D78 80025178 02014821 */  addu        $t1, $s0, $at
    /* 025D7C 8002517C 2D210010 */  sltiu       $at, $t1, 0x10
    /* 025D80 80025180 1020000A */  beqz        $at, .L800251AC
    /* 025D84 80025184 00094880 */   sll        $t1, $t1, 2
    /* 025D88 80025188 3C01800A */  lui         $at, %hi(jtbl_800A32C0)
    /* 025D8C 8002518C 00290821 */  addu        $at, $at, $t1
    /* 025D90 80025190 8C2932C0 */  lw          $t1, %lo(jtbl_800A32C0)($at)
    /* 025D94 80025194 01200008 */  jr          $t1
    /* 025D98 80025198 00000000 */   nop
  .L8002519C:
    /* 025D9C 8002519C 1000000A */  b           .L800251C8
    /* 025DA0 800251A0 24030006 */   addiu      $v1, $zero, 0x6
  .L800251A4:
    /* 025DA4 800251A4 10000008 */  b           .L800251C8
    /* 025DA8 800251A8 24030007 */   addiu      $v1, $zero, 0x7
  .L800251AC:
    /* 025DAC 800251AC 3C048009 */  lui         $a0, %hi(D_80090A90)
    /* 025DB0 800251B0 24840A90 */  addiu       $a0, $a0, %lo(D_80090A90)
    /* 025DB4 800251B4 90820000 */  lbu         $v0, 0x0($a0)
    /* 025DB8 800251B8 24430004 */  addiu       $v1, $v0, 0x4
    /* 025DBC 800251BC 384A0001 */  xori        $t2, $v0, 0x1
    /* 025DC0 800251C0 306300FF */  andi        $v1, $v1, 0xFF
    /* 025DC4 800251C4 A08A0000 */  sb          $t2, 0x0($a0)
  .L800251C8:
    /* 025DC8 800251C8 306400FF */  andi        $a0, $v1, 0xFF
    /* 025DCC 800251CC 00042200 */  sll         $a0, $a0, 8
    /* 025DD0 800251D0 3C010604 */  lui         $at, (0x6040000 >> 16)
    /* 025DD4 800251D4 00102E00 */  sll         $a1, $s0, 24
    /* 025DD8 800251D8 00052E03 */  sra         $a1, $a1, 24
    /* 025DDC 800251DC 0C0061D3 */  jal         func_8001874C
    /* 025DE0 800251E0 00812025 */   or         $a0, $a0, $at
  .L800251E4:
    /* 025DE4 800251E4 8FBF001C */  lw          $ra, 0x1C($sp)
  .L800251E8:
    /* 025DE8 800251E8 8FB00018 */  lw          $s0, 0x18($sp)
    /* 025DEC 800251EC 27BD0038 */  addiu       $sp, $sp, 0x38
    /* 025DF0 800251F0 03E00008 */  jr          $ra
    /* 025DF4 800251F4 00000000 */   nop
