#!/usr/bin/env python3
"""Render the public root-layout COVERAGE.md from tracked source pragmas.

This is independent of the generated asm tree and the ROM. It can inspect
HEAD, a revision, or the staged index. The existing COVERAGE.md table supplies
per-file baseline totals because the public repository does not contain the
private repository's baseline commit.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


BASELINE_TOTAL = 10_532
START_MARKER = "<!-- AUTO_COVERAGE:START -->"
END_MARKER = "<!-- AUTO_COVERAGE:END -->"
GENERATED_HEADER = "<!-- Generated by ci/update_coverage.py. Do not edit by hand. -->"
PRAGMA_PATTERN = r'GLOBAL_ASM\("asm/us/nonmatchings/[^" ]+/[^"/]+\.s"\)'
PRAGMA_RE = re.compile(r'GLOBAL_ASM\("asm/us/nonmatchings/[^" ]+/([^"/]+)\.s"\)')
TABLE_RE = re.compile(r"^\| `([^`]+)` \| [0-9,]+ \| ([0-9,]+) \|")


@dataclass(frozen=True)
class CoverageSnapshot:
    covered: int
    total: int
    percentage: float
    remaining_by_file: dict[str, int]


def git_grep(repo_root: Path, revision: str, staged: bool) -> str:
    # Keep the safety exception scoped to this invocation. Public checkouts
    # may be mounted or created by a different account on a self-hosted host.
    safe_directory = repo_root.resolve().as_posix()
    command = ["git", "-c", f"safe.directory={safe_directory}", "-C", str(repo_root), "grep", "--no-color"]
    if staged:
        command.append("--cached")
    command += ["-E", PRAGMA_PATTERN]
    if not staged:
        command.append(revision)
    command += ["--", "src"]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode not in (0, 1):
        raise RuntimeError(result.stderr.strip() or f"git grep failed: {result.returncode}")
    return result.stdout


def owners_by_file(repo_root: Path, revision: str, staged: bool) -> dict[str, set[str]]:
    output = git_grep(repo_root, revision, staged)
    prefix = "" if staged else f"{revision}:"
    owners: dict[str, set[str]] = {}
    for line in output.splitlines():
        text = line[len(prefix):] if prefix and line.startswith(prefix) else line
        path, separator, content = text.partition(":")
        if not separator:
            continue
        match = PRAGMA_RE.search(content)
        if match:
            owners.setdefault(path, set()).add(match.group(1))
    return owners


def baseline_by_file(path: Path) -> dict[str, int]:
    if not path.exists():
        return {}
    result: dict[str, int] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = TABLE_RE.match(line)
        if match:
            result[match.group(1)] = int(match.group(2).replace(",", ""))
    return result


def snapshot(repo_root: Path, revision: str, staged: bool) -> CoverageSnapshot:
    owners = owners_by_file(repo_root, revision, staged)
    remaining_by_file = {path: len(names) for path, names in owners.items()}
    remaining = sum(remaining_by_file.values())
    covered = max(BASELINE_TOTAL - remaining, 0)
    return CoverageSnapshot(
        covered=covered,
        total=BASELINE_TOTAL,
        percentage=covered / BASELINE_TOTAL * 100.0,
        remaining_by_file=remaining_by_file,
    )


def render(snapshot_value: CoverageSnapshot, baseline: dict[str, int]) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "# Decompilation coverage",
        "",
        START_MARKER,
        f"- US functions with C implementations: **{snapshot_value.covered:,} / {snapshot_value.total:,} ({snapshot_value.percentage:.1f}%)**",
        f"- Remaining `GLOBAL_ASM` owners: **{snapshot_value.total - snapshot_value.covered:,}**",
        f"- Baseline: **{snapshot_value.total:,}** US `GLOBAL_ASM` owners in the original pragma snapshot",
        END_MARKER,
        "",
        "## Remaining owners by source file",
        "",
        "| File | Remaining | Baseline total | Percent complete |",
        "| --- | ---: | ---: | ---: |",
    ]
    for path in sorted(snapshot_value.remaining_by_file):
        remaining = snapshot_value.remaining_by_file[path]
        total = baseline.get(path, remaining)
        percentage = max(total - remaining, 0) / total * 100.0 if total else 0.0
        lines.append(f"| `{path}` | {remaining:,} | {total:,} | {percentage:.1f}% |")
    if not snapshot_value.remaining_by_file:
        lines.append("_No source files with remaining `GLOBAL_ASM` owners._")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=None)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--baseline", type=Path, default=None)
    parser.add_argument("--revision", default="HEAD")
    parser.add_argument("--staged", action="store_true")
    parser.add_argument("--check", action="store_true", help="fail if the output is not current")
    args = parser.parse_args()

    repo_root = (args.repo_root or Path(__file__).resolve().parent.parent).resolve()
    output = (args.output or repo_root / "COVERAGE.md").resolve()
    baseline_path = (args.baseline or output).resolve()
    generated = render(snapshot(repo_root, args.revision, args.staged), baseline_by_file(baseline_path))
    existing = output.read_text(encoding="utf-8") if output.exists() else None

    if args.check:
        if existing == generated:
            print(f"coverage: current ({output})")
            return 0
        print(f"coverage: stale ({output})")
        return 1

    if existing != generated:
        output.write_text(generated, encoding="utf-8")
        print(f"coverage: updated {output}")
    else:
        print(f"coverage: unchanged {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
